/* 1001 Classical — build data.js from the curated recordings table below.
 * Each recording is a landmark/benchmark recording of a canonical work.
 * Fields: t=work title (searchable EN), zh=中文曲名, c=composer(EN key),
 *   perf=演绎(指挥/乐团/独奏), y=录音年, label, era, g=[体裁], ins=[乐器], m=[心情], r=中文导读
 */
import { writeFileSync } from "node:fs";

const ERAS = [
  {key:"medieval",name:"Medieval / 中世纪",years:"约 1150–1400",keywords:"素歌 · 复调初生 · 修道院",desc:"西方古典音乐的源头。单声的格里高利圣咏在修道院回响，随后奥尔加农让第二条声部升起——复调由此诞生。希尔德加德的通神歌咏、佩罗坦的巴黎圣母院乐派，是这段幽深岁月里最亮的光。"},
  {key:"renaissance",name:"Renaissance / 文艺复兴",years:"约 1400–1600",keywords:"无伴奏合唱 · 对位 · 弥撒经文歌",desc:"人声复调的黄金时代。若斯坎、帕勒斯特里那、塔利斯把多条声部编织成澄澈交融的织体，宗教改革与反宗教改革在弥撒与经文歌里角力，四十声部的《Spem in Alium》是纯人声所能抵达的奇迹。"},
  {key:"baroque",name:"Baroque / 巴洛克",years:"1600–1750",keywords:"通奏低音 · 赋格 · 协奏曲 · 歌剧诞生",desc:"从蒙特威尔第的第一部歌剧到巴赫的赋格宇宙。数字低音撑起华丽的装饰旋律，维瓦尔第定型协奏曲，亨德尔征服伦敦歌剧院，而巴赫把这一切技法推向前无古人、后无来者的完满。"},
  {key:"classical",name:"Classical / 古典主义",years:"约 1730–1820",keywords:"奏鸣曲式 · 均衡 · 交响曲成型",desc:"理性、均衡与清晰的时代。海顿确立交响曲与弦乐四重奏的范式，莫扎特让旋律臻于天然的完美，贝多芬则从这里出发，用意志把古典的框架撑向浪漫的门槛。"},
  {key:"romantic",name:"Romantic / 浪漫主义",years:"约 1800–1910",keywords:"个人情感 · 标题音乐 · 歌剧巨制 · 交响诗",desc:"音乐成为自我的告白。舒伯特的艺术歌曲、肖邦的夜曲、瓦格纳的乐剧、柴科夫斯基的绝望、马勒的宇宙——形式不断膨胀，情感不断加压，直到晚期浪漫在辉煌中走向裂变。"},
  {key:"modern",name:"Modern / 现代",years:"约 1900–1975",keywords:"调性瓦解 · 节奏革命 · 新语言",desc:"二十世纪把一切推倒重来。德彪西模糊调性，斯特拉文斯基的《春之祭》引发暴动，勋伯格发明十二音，巴托克、肖斯塔科维奇、布里顿在战争与极权的阴影下，为古典音乐找到全新的骨骼与良心。"},
  {key:"contemporary",name:"Contemporary / 当代",years:"约 1975–今",keywords:"简约主义 · 神圣极简 · 跨界",desc:"在先锋的极端之后，音乐重新伸手拥抱听众。赖希与格拉斯的简约脉动、佩尔特与戈雷茨基的神圣静默、约翰·亚当斯的新浪漫,让当代古典既能进音乐厅，也能进电影院与流行榜。"}
];

const MOODS = ["夜晚","沉思","激昂","疗愈","庄严","悲伤","喜悦","专注","壮丽","亲密"];
const INSTRUMENTS = ["管弦乐团","钢琴","小提琴","大提琴","人声","合唱","管风琴","羽管键琴","弦乐四重奏","长笛","单簧管","小号","吉他","打击乐"];
const FEATURED = [
  "Johann Sebastian Bach","Wolfgang Amadeus Mozart","Ludwig van Beethoven",
  "Franz Schubert","Frédéric Chopin","Johannes Brahms","Richard Wagner",
  "Pyotr Ilyich Tchaikovsky","Gustav Mahler","Claude Debussy",
  "Igor Stravinsky","Dmitri Shostakovich","Arvo Pärt","Steve Reich"
];

// ---- 曲库（均为公认的标杆/传奇录音；导读为入门向中文解说）----
const R = [
// 中世纪
["A Feather on the Breath of God","《上帝气息中的一片羽毛》","Hildegard von Bingen","Gothic Voices · Christopher Page",1982,"Hyperion","medieval",["合唱/宗教","声乐"],["人声","合唱"],["沉思","疗愈","庄严"],"十二世纪修道院长、神秘主义者、也是最早留名的作曲家之一。她的单声圣咏音域宽广、旋律像藤蔓般攀升，这张1982年的录音让希尔德加德在千年后成为畅销榜上的名字。"],
["Pérotin","《佩罗坦》","Pérotin","The Hilliard Ensemble",1989,"ECM New Series","medieval",["合唱/宗教","声乐"],["人声","合唱"],["庄严","沉思"],"巴黎圣母院乐派的巅峰。佩罗坦把素歌拉长成两声、三声、四声的奥尔加农，人声在大教堂的空间里层层堆叠——这是西方复调最早的宏伟建筑，希利亚德合唱团的演绎澄澈通透。"],
["Messe de Nostre Dame","《圣母弥撒》","Guillaume de Machaut","Ensemble Organum · Marcel Pérès",1996,"Harmonia Mundi","medieval",["合唱/宗教","声乐"],["人声","合唱"],["庄严","沉思"],"史上第一部由单一作曲家完成的完整弥撒套曲。马肖既是诗人也是作曲家，这部十四世纪的杰作把新艺术（Ars Nova）的节奏复杂性写进了神圣仪式。"],
// 文艺复兴
["Missa Pange Lingua","《潘吉舌弥撒》","Josquin des Prez","The Tallis Scholars · Peter Phillips",1986,"Gimell","renaissance",["合唱/宗教","声乐"],["人声","合唱"],["庄严","沉思","疗愈"],"若斯坎是文艺复兴盛期最伟大的复调大师，被同代人视为‘音符的主人’。塔利斯学者合唱团的这版模仿对位清澈如水晶，是进入无伴奏合唱世界的最佳门径。"],
["Missa Papae Marcelli","《马尔切鲁斯教皇弥撒》","Giovanni Pierluigi da Palestrina","The Tallis Scholars · Peter Phillips",1980,"Gimell","renaissance",["合唱/宗教","声乐"],["人声","合唱"],["庄严","疗愈"],"传说这部弥撒‘拯救了教会音乐’——它证明复调也能让歌词清晰可辨。帕勒斯特里那的对位平滑无瑕，成为此后数百年宗教复调的标准范本。"],
["Spem in Alium","《寄望于他》","Thomas Tallis","The Tallis Scholars · Peter Phillips",1985,"Gimell","renaissance",["合唱/宗教","声乐"],["人声","合唱"],["壮丽","庄严"],"四十个独立声部同时歌唱——文艺复兴合唱的珠穆朗玛。塔利斯让人声像光穿过彩窗一样在空间中环绕流动，一次纯人声的听觉奇观。"],
["Missa Assumpta est Maria","《圣母升天弥撒》","William Byrd","The Tallis Scholars",1984,"Gimell","renaissance",["合唱/宗教","声乐"],["人声","合唱"],["庄严","沉思"],"英国最伟大的文艺复兴作曲家，在新教英格兰坚守天主教信仰，把这份隐秘的虔诚写进精雕细琢的弥撒。塔利斯学者合唱团的英伦音色端庄而深情。"],
["Vespro della Beata Vergine","《圣母晚祷》","Claudio Monteverdi","John Eliot Gardiner · English Baroque Soloists",1989,"Archiv","baroque",["合唱/宗教","声乐"],["人声","合唱","管弦乐团"],["壮丽","庄严"],"横跨文艺复兴与巴洛克的巨构。蒙特威尔第把古老的素歌与崭新的歌剧笔法熔于一炉，加德纳在圣马可教堂的这版录音气势恢宏，是1610年这部杰作的标杆诠释。"],
["L'Orfeo","《奥菲欧》","Claudio Monteverdi","Nikolaus Harnoncourt · Concentus Musicus Wien",1968,"Teldec","baroque",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","庄严"],"西方第一部真正意义上的歌剧。蒙特威尔第用音乐讲述奥菲欧下冥界寻妻的故事，哈农库特的本真演奏复原了1607年的音响世界，歌剧艺术从这里启程。"],
// 巴洛克
["Goldberg Variations (1955)","《哥德堡变奏曲》（1955）","Johann Sebastian Bach","Glenn Gould",1955,"Columbia","baroque",["独奏/键盘"],["钢琴"],["专注","激昂","喜悦"],"二十二岁的古尔德横空出世，以疾风般的速度、水晶般的清晰重新定义了巴赫。这张唱片让原本冷门的《哥德堡》成为古典音乐史上最著名的录音之一。"],
["Goldberg Variations (1981)","《哥德堡变奏曲》（1981）","Johann Sebastian Bach","Glenn Gould",1981,"CBS","baroque",["独奏/键盘"],["钢琴"],["沉思","专注","亲密"],"二十六年后，古尔德在生命尽头重录《哥德堡》——速度放慢，咏叹调如临终的低语。与1955版并置聆听，是一部关于时间与人生的无言之诗。"],
["Cello Suites","《无伴奏大提琴组曲》","Johann Sebastian Bach","Pablo Casals",1939,"EMI","baroque",["独奏/键盘","室内乐"],["大提琴"],["沉思","亲密","庄严"],"卡萨尔斯十三岁在旧书店偶得乐谱，练了十二年才敢公开演奏，最终在1930年代把这套被遗忘的组曲录成传世经典。没有他，就没有今天大提琴的圣经。"],
["Sonatas and Partitas for Solo Violin","《无伴奏小提琴奏鸣曲与组曲》","Johann Sebastian Bach","Nathan Milstein",1973,"Deutsche Grammophon","baroque",["独奏/键盘","室内乐"],["小提琴"],["专注","沉思","庄严"],"一把小提琴独自撑起赋格与恰空的复调宇宙。米尔斯坦的演绎兼具智性的清晰与贵族气度，尤其《d小调恰空》被誉为‘写在一根弦上的整个世界’。"],
["Mass in B minor","《b小调弥撒》","Johann Sebastian Bach","John Eliot Gardiner · Monteverdi Choir",1985,"Archiv","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团"],["壮丽","庄严","疗愈"],"巴赫毕生对位与信仰的总结，一座声音的大教堂。加德纳率蒙特威尔第合唱团以本真乐器演绎，明亮而充满动能，是这部人类杰作最受推崇的现代录音之一。"],
["St Matthew Passion","《马太受难曲》","Johann Sebastian Bach","Karl Richter · Münchener Bach-Orchester",1958,"Archiv","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团","人声"],["悲伤","庄严","沉思"],"西方宗教音乐的顶峰。巴赫用近三小时讲述基督受难，双合唱、双乐团交织出无尽的悲悯。里希特1958年的这版庄严肃穆，几代人心中的权威诠释。"],
["Brandenburg Concertos","《勃兰登堡协奏曲》","Johann Sebastian Bach","Trevor Pinnock · The English Concert",1982,"Archiv","baroque",["协奏曲","管弦乐"],["管弦乐团","羽管键琴"],["喜悦","激昂","专注"],"六首献给勃兰登堡侯爵的协奏曲，是巴洛克大协奏曲的百科全书。品诺克的本真演奏轻盈灵动，第五首里羽管键琴的华彩段是键盘协奏曲的开山之作。"],
["The Well-Tempered Clavier","《平均律键盘曲集》","Johann Sebastian Bach","Sviatoslav Richter",1973,"Melodiya","baroque",["独奏/键盘"],["钢琴"],["专注","沉思"],"被誉为键盘音乐的‘旧约圣经’——遍历二十四个大小调的前奏曲与赋格。里希特的演绎沉静内敛、结构如建筑般清晰，是钢琴家一生研习的对象。"],
["Messiah","《弥赛亚》","George Frideric Handel","Christopher Hogwood · Academy of Ancient Music",1980,"L'Oiseau-Lyre","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团"],["壮丽","喜悦","庄严"],"《哈利路亚》大合唱响起时全场起立——这一传统延续至今。亨德尔仅用二十四天写成这部清唱剧，霍格伍德的本真版还原了1741年首演的轻盈质感。"],
["Water Music / Music for the Royal Fireworks","《水上音乐 · 皇家焰火音乐》","George Frideric Handel","John Eliot Gardiner · English Baroque Soloists",1991,"Philips","baroque",["管弦乐"],["管弦乐团","小号"],["喜悦","壮丽","激昂"],"为泰晤士河上的皇家游船与庆典焰火而作的户外盛典音乐。铜管辉煌、舞曲明快，是巴洛克最让人心情舒畅的管弦乐，加德纳演来神采飞扬。"],
["The Four Seasons","《四季》","Antonio Vivaldi","Nigel Kennedy · English Chamber Orchestra",1989,"EMI","baroque",["协奏曲"],["小提琴","管弦乐团"],["喜悦","激昂","壮丽"],"史上最著名的古典音乐之一。维瓦尔第用四首小提琴协奏曲描绘四季风景——鸟鸣、暴风雪、猎号。肯尼迪1989年的这张唱片卖出逾两百万，让《四季》红遍全球。"],
["Dido and Aeneas","《狄多与埃涅阿斯》","Henry Purcell","William Christie · Les Arts Florissants",1994,"Erato","baroque",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","亲密"],"英国巴洛克歌剧的孤峰。全剧不到一小时，却以狄多临终的咏叹调《当我长眠地下》达到心碎的顶点——一条固定低音上无尽下行的悲叹，三百年来催人泪下。"],
["Keyboard Sonatas","《键盘奏鸣曲》","Domenico Scarlatti","Vladimir Horowitz",1964,"Columbia","baroque",["独奏/键盘"],["钢琴"],["喜悦","激昂","亲密"],"斯卡拉蒂写下五百五十多首单乐章奏鸣曲，充满西班牙吉他的扫弦、响板与交叉手的炫技。霍洛维茨精选的这组以钢琴演绎，晶莹剔透，证明它们跨越乐器依然鲜活。"],
// 古典主义
["The Creation","《创世纪》","Joseph Haydn","Herbert von Karajan · Berliner Philharmoniker",1969,"Deutsche Grammophon","classical",["合唱/宗教","声乐"],["合唱","管弦乐团"],["壮丽","喜悦","庄严"],"‘要有光’——当合唱在此处爆发出C大调时，是古典音乐里最震撼的瞬间之一。年迈的海顿以这部清唱剧描绘天地初开，卡拉扬的演绎恢弘而充满敬畏。"],
["Symphonies Nos. 93–104 'London'","《伦敦交响曲》","Joseph Haydn","Colin Davis · Concertgebouw / Royal Concertgebouw",1994,"Philips","classical",["交响曲"],["管弦乐团"],["喜悦","激昂","壮丽"],"‘交响曲之父’晚年为伦敦写下的十二部杰作，机智、惊喜（第94号的‘惊愕’）与工艺的巅峰。听海顿，就是听交响曲这一形式如何被一位大师彻底定型。"],
["Le nozze di Figaro","《费加罗的婚礼》","Wolfgang Amadeus Mozart","Erich Kleiber · Wiener Philharmoniker",1955,"Decca","classical",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","激昂","亲密"],"歌剧史上最完美的喜剧之一。莫扎特把一部关于阶级与爱情的闹剧写成了人性的百科全书。老克莱伯1955年的维也纳录音优雅流畅，公认的黄金标准。"],
["Don Giovanni","《唐·乔万尼》","Wolfgang Amadeus Mozart","Carlo Maria Giulini · Philharmonia Orchestra",1959,"EMI","classical",["歌剧","声乐"],["人声","管弦乐团"],["激昂","庄严","夜晚"],"喜剧与恐怖、诱惑与惩罚交织的‘戏剧诙谐’。花花公子唐·乔万尼被石像拖入地狱的终场令人战栗。朱里尼这版云集Wächter、Schwarzkopf等名角，被誉为不可超越。"],
["Die Zauberflöte","《魔笛》","Wolfgang Amadeus Mozart","Otto Klemperer · Philharmonia Orchestra",1964,"EMI","classical",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","庄严","壮丽"],"莫扎特最后的歌剧，一部融合童话、共济会象征与崇高人性的德语歌唱剧。夜后的花腔高音家喻户晓，克伦佩勒的演绎庄重宏大，兼具童真与哲思。"],
["Requiem","《安魂曲》","Wolfgang Amadeus Mozart","Karl Böhm · Wiener Philharmoniker",1971,"Deutsche Grammophon","classical",["合唱/宗教","声乐"],["合唱","管弦乐团"],["悲伤","庄严","沉思"],"莫扎特未及写完便撒手人寰的绝笔，一部为自己而作的安魂弥撒。《落泪之日》的哀恸令人心碎。伯姆与维也纳爱乐的演绎沉痛而崇高，是这部传奇之作的经典诠释。"],
["Piano Concertos Nos. 20 & 21","《第20 · 21钢琴协奏曲》","Wolfgang Amadeus Mozart","Clara Haskil · Ferenc Fricsay",1954,"Deutsche Grammophon","classical",["协奏曲"],["钢琴","管弦乐团"],["亲密","沉思","喜悦"],"莫扎特二十七首钢琴协奏曲是他最私密的自画像。d小调（第20号）的戏剧性与C大调（第21号）如歌的行板家喻户晓。哈斯基尔的触键纯净通透，被奉为莫扎特的化身。"],
["Symphonies Nos. 40 & 41 'Jupiter'","《第40 · 41“朱庇特”交响曲》","Wolfgang Amadeus Mozart","Bruno Walter · Columbia Symphony",1960,"Columbia","classical",["交响曲"],["管弦乐团"],["激昂","壮丽","悲伤"],"莫扎特最后三部交响曲的两座高峰：g小调（第40号）的忧郁悸动与‘朱庇特’（第41号）终曲五重赋格的辉煌。瓦尔特的演绎温暖而有呼吸感，古典交响的典范。"],
["Clarinet Concerto","《单簧管协奏曲》","Wolfgang Amadeus Mozart","Jack Brymer · Thomas Beecham",1959,"EMI","classical",["协奏曲"],["单簧管","管弦乐团"],["亲密","沉思","疗愈"],"莫扎特生命最后一年写下的天鹅之歌，为单簧管的温润音色量身定制。第二乐章的柔板宁静得近乎透明，是抚慰人心的至美旋律。"],
["Symphony No. 9 'Choral'","《第九交响曲“合唱”》","Ludwig van Beethoven","Wilhelm Furtwängler · Bayreuth Festival",1951,"EMI","classical",["交响曲","合唱/宗教"],["管弦乐团","合唱"],["壮丽","激昂","庄严"],"人类理想的音乐宣言。全聋的贝多芬在末乐章引入人声，让席勒的《欢乐颂》响彻云霄。富特文格勒1951年拜罗伊特重开音乐节的这场现场，被公认为史上最伟大的‘贝九’。"],
["Symphonies (Complete)","《贝多芬交响曲全集》","Ludwig van Beethoven","Herbert von Karajan · Berliner Philharmoniker",1963,"Deutsche Grammophon","classical",["交响曲"],["管弦乐团"],["壮丽","激昂","专注"],"卡拉扬与柏林爱乐1963年的全集，是立体声时代最具影响力的贝多芬。铿锵有力、光泽饱满，塑造了几代人对这九部交响曲的听觉印象，至今仍是入门首选。"],
["Symphonies Nos. 5 & 7","《第五 · 第七交响曲》","Ludwig van Beethoven","Carlos Kleiber · Wiener Philharmoniker",1974,"Deutsche Grammophon","classical",["交响曲"],["管弦乐团"],["激昂","壮丽","喜悦"],"‘命运在敲门’——史上最著名的四个音符。小克莱伯这版第五、第七交响曲以雷霆万钧的能量和惊人的精确度，被众多乐评评为立体声史上最伟大的唱片，无可争议的标杆。"],
["Piano Sonatas (Complete)","《贝多芬钢琴奏鸣曲全集》","Ludwig van Beethoven","Artur Schnabel",1935,"EMI","classical",["独奏/键盘"],["钢琴"],["沉思","激昂","专注"],"三十二首钢琴奏鸣曲被称为钢琴家的‘新约圣经’。施纳贝尔在1930年代第一个录下全集，技术偶有瑕疵却充满思想的重量，至今仍是最深刻的贝多芬诠释之一。"],
["Violin Concerto","《D大调小提琴协奏曲》","Ludwig van Beethoven","Jascha Heifetz · Charles Munch",1955,"RCA","classical",["协奏曲"],["小提琴","管弦乐团"],["庄严","壮丽","亲密"],"小提琴协奏曲的王者，宽广、崇高、如歌。海菲茨以无懈可击的技术与贵族气质演绎，明希的伴奏气度恢宏，是这部‘协奏曲之王’最耀眼的版本之一。"],
["Late String Quartets","《晚期弦乐四重奏》","Ludwig van Beethoven","Busch Quartet",1936,"EMI","classical",["室内乐"],["弦乐四重奏"],["沉思","悲伤","庄严"],"贝多芬最后的音乐遗言，超越时代一个世纪的孤独沉思。布什四重奏1930年代的历史录音带着炽热的信念，把这些‘从另一个星球传来’的作品演绎得撕心裂肺。"],
// 浪漫主义
["Winterreise","《冬之旅》","Franz Schubert","Dietrich Fischer-Dieskau · Gerald Moore",1972,"Deutsche Grammophon","romantic",["声乐/艺术歌曲","室内乐"],["人声","钢琴"],["悲伤","夜晚","沉思"],"艺术歌曲的珠穆朗玛。二十四首歌串成一个失恋者在寒冬中的孤独漂泊，直至遇见街头的摇琴老人。费舍尔-迪斯考的男中音与摩尔的钢琴,是这部套曲不可撼动的经典。"],
["String Quintet in C","《C大调弦乐五重奏》","Franz Schubert","Isaac Stern · Pablo Casals · Prades Festival",1952,"Columbia","romantic",["室内乐"],["弦乐四重奏","大提琴"],["沉思","悲伤","亲密","疗愈"],"舒伯特去世前两个月的绝笔，室内乐无可争议的顶峰。第二乐章的柔板是时间静止的天堂,又被中段的绝望撕裂——听过的人都难以忘怀那种美到极致的忧伤。"],
["Nocturnes","《夜曲》","Frédéric Chopin","Arthur Rubinstein",1965,"RCA","romantic",["独奏/键盘"],["钢琴"],["夜晚","亲密","沉思","疗愈"],"钢琴诗人最私密的低语。二十一首夜曲把歌剧的咏叹调移植到黑白琴键上，如夜色中的独白。鲁宾斯坦优雅高贵、不事煽情的演绎，被公认为肖邦的正统。"],
["Ballades & Scherzos","《叙事曲与谐谑曲》","Frédéric Chopin","Krystian Zimerman",1987,"Deutsche Grammophon","romantic",["独奏/键盘"],["钢琴"],["激昂","悲伤","壮丽"],"四首叙事曲是肖邦最宏大的钢琴叙事，戏剧性的起伏如无字的小说。齐默尔曼的演绎技术完美、结构宏伟又饱含诗意，是当代肖邦的标杆录音。"],
["Piano Concerto No. 1 & Kinderszenen","《钢琴协奏曲 · 童年情景》","Robert Schumann","Sviatoslav Richter · Witold Rowicki",1958,"Deutsche Grammophon","romantic",["协奏曲","独奏/键盘"],["钢琴","管弦乐团"],["亲密","激昂","沉思"],"舒曼把文学的想象注入音乐。a小调钢琴协奏曲热情奔涌,《童年情景》里的《梦幻曲》则是家喻户晓的温柔。里希特兼具火焰与诗意，是舒曼理想的代言人。"],
["Violin Concerto","《e小调小提琴协奏曲》","Felix Mendelssohn","Jascha Heifetz · Charles Munch",1959,"RCA","romantic",["协奏曲"],["小提琴","管弦乐团"],["喜悦","激昂","亲密"],"最受喜爱的小提琴协奏曲之一，开篇即由独奏直入如歌的主题，一气呵成。海菲茨的演绎飞扬璀璨、气息绵长，把门德尔松的优雅与激情展现得淋漓尽致。"],
["Symphonie fantastique","《幻想交响曲》","Hector Berlioz","Charles Munch · Boston Symphony",1962,"RCA","romantic",["交响曲","管弦乐"],["管弦乐团"],["激昂","夜晚","壮丽"],"标题音乐的开山巨作。柏辽兹用音乐讲述一个艺术家因单恋服毒、坠入断头台与女巫夜宴幻梦的故事。配器天才横溢,明希与波士顿交响的演绎火花四溅。"],
["Symphony No. 4","《第四交响曲》","Johannes Brahms","Carlos Kleiber · Wiener Philharmoniker",1980,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["悲伤","激昂","庄严"],"勃拉姆斯交响曲的绝唱，末乐章以古老的帕萨卡利亚变奏形式写成三十段悲壮的变奏。小克莱伯的演绎兼具结构的严谨与燃烧般的激情,是这部作品的传奇版本。"],
["Violin Concerto","《D大调小提琴协奏曲》","Johannes Brahms","David Oistrakh · George Szell",1969,"EMI","romantic",["协奏曲"],["小提琴","管弦乐团"],["庄严","壮丽","激昂"],"与贝多芬、门德尔松并称的德奥小提琴协奏曲高峰，交响性厚重、情感深沉。奥伊斯特拉赫宽广温暖的音色与塞尔精准的伴奏，被视为最权威的诠释之一。"],
["Ein deutsches Requiem","《德意志安魂曲》","Johannes Brahms","Otto Klemperer · Philharmonia",1961,"EMI","romantic",["合唱/宗教","声乐"],["合唱","管弦乐团"],["悲伤","疗愈","庄严"],"不为死者、而为生者慰藉的安魂曲。勃拉姆斯用德语圣经文本写下‘凡有血气的，尽都如草’的沉思。克伦佩勒的演绎庄严宽厚,是抚慰哀伤最深沉的音乐。"],
["Piano Sonata in B minor","《b小调钢琴奏鸣曲》","Franz Liszt","Martha Argerich",1971,"Deutsche Grammophon","romantic",["独奏/键盘"],["钢琴"],["激昂","壮丽","夜晚"],"浪漫主义钢琴文献的巅峰,一个乐章内浓缩了整部交响曲的戏剧。李斯特把炫技升华为哲学。阿格里奇的演绎狂放而精准,一泻千里,令人屏息。"],
["La traviata","《茶花女》","Giuseppe Verdi","Carlos Kleiber · Bayerisches Staatsorchester",1977,"Deutsche Grammophon","romantic",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","亲密","激昂"],"世界上上演最多的歌剧之一。威尔第把小仲马笔下交际花的爱情悲剧写成催人泪下的旋律。小克莱伯指挥、科特鲁巴斯主演的这版，激情与细腻兼备。"],
["Otello","《奥赛罗》","Giuseppe Verdi","Herbert von Karajan · Wiener Philharmoniker",1961,"Decca","romantic",["歌剧","声乐"],["人声","管弦乐团"],["激昂","悲伤","壮丽"],"威尔第晚年根据莎士比亚写就的悲剧杰作，把意大利歌剧的戏剧张力推向极致。开场暴风雨的合唱惊心动魄，德尔·摩纳哥的‘奥赛罗’气壮山河。"],
["Messa da Requiem","《安魂弥撒》","Giuseppe Verdi","Fritz Reiner · Wiener Philharmoniker",1960,"Decca","romantic",["合唱/宗教","声乐"],["合唱","管弦乐团","人声"],["壮丽","激昂","庄严"],"被戏称为‘威尔第最好的歌剧’——《末日经》的定音鼓与铜管如天崩地裂，是合唱曲目中最富戏剧性的震撼。莱纳的演绎气势磅礴,录音效果传奇。"],
["Der Ring des Nibelungen","《尼伯龙根的指环》","Richard Wagner","Georg Solti · Wiener Philharmoniker",1965,"Decca","romantic",["歌剧","声乐"],["人声","管弦乐团"],["壮丽","激昂","庄严"],"录音史上的登月工程。索尔蒂历时七年（1958–65）录下这部长达十五小时的四联剧，制作人卡尔肖开创性的立体声舞台效果空前绝后。常被评为史上最伟大的录音。"],
["Tristan und Isolde","《特里斯坦与伊索尔德》","Richard Wagner","Wilhelm Furtwängler · Philharmonia",1952,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["夜晚","激昂","悲伤"],"改变了音乐史的作品——开篇的‘特里斯坦和弦’悬而不决,松动了调性的根基,预示了整个二十世纪。富特文格勒的演绎把这部爱与死的乐剧演绎得如暗夜潮汐。"],
["Symphony No. 6 'Pathétique'","《第六交响曲“悲怆”》","Pyotr Ilyich Tchaikovsky","Yevgeny Mravinsky · Leningrad Philharmonic",1960,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["悲伤","激昂","夜晚"],"柴科夫斯基首演九天后猝逝的绝笔,末乐章一反常规以缓慢的哀歌沉入死寂。穆拉文斯基与列宁格勒爱乐的这版冷峻锋利、张力逼人,被公认为不可逾越的诠释。"],
["Piano Concerto No. 1","《第一钢琴协奏曲》","Pyotr Ilyich Tchaikovsky","Sviatoslav Richter · Herbert von Karajan",1962,"Deutsche Grammophon","romantic",["协奏曲"],["钢琴","管弦乐团"],["激昂","壮丽","喜悦"],"开篇气势磅礴的和弦无人不晓，是最受欢迎的钢琴协奏曲。里希特钢铁般的力量与卡拉扬的辉煌交响相撞，成就了一版充满火花与张力的经典。"],
["Violin Concerto","《D大调小提琴协奏曲》","Pyotr Ilyich Tchaikovsky","Jascha Heifetz · Fritz Reiner",1957,"RCA","romantic",["协奏曲"],["小提琴","管弦乐团"],["激昂","喜悦","壮丽"],"技巧与旋律兼美的小提琴协奏曲,曾被批评‘无法演奏’,如今是每位大师的试金石。海菲茨以令人瞠目的速度与精准演绎,凌厉璀璨,酣畅淋漓。"],
["Symphony No. 9 'From the New World'","《第九交响曲“自新大陆”》","Antonín Dvořák","Herbert von Karajan · Wiener Philharmoniker",1985,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["激昂","壮丽","沉思"],"德沃夏克旅美期间写下的思乡之作,融入了黑人灵歌与印第安曲调的气息。第二乐章的英国管旋律《念故乡》家喻户晓。卡拉扬的演绎大气磅礴又饱含深情。"],
["Cello Concerto","《b小调大提琴协奏曲》","Antonín Dvořák","Mstislav Rostropovich · Herbert von Karajan",1969,"Deutsche Grammophon","romantic",["协奏曲"],["大提琴","管弦乐团"],["悲伤","壮丽","沉思"],"大提琴协奏曲的皇冠。德沃夏克把思乡、爱情与告别写进这部交响性巨作。罗斯特罗波维奇如歌的琴声与卡拉扬的乐队水乳交融，被誉为难以超越的黄金组合。"],
["Piano Concerto & Peer Gynt","《钢琴协奏曲 · 培尔·金特》","Edvard Grieg","Stephen Kovacevich · Colin Davis",1971,"Philips","romantic",["协奏曲","管弦乐"],["钢琴","管弦乐团"],["激昂","喜悦","壮丽"],"格里格a小调钢琴协奏曲开篇的定音鼓与倾泻而下的和弦是浪漫主义的名片；《培尔·金特》中的《晨景》与《山魔王的大厅》更是无人不晓的北欧音画。"],
["Pictures at an Exhibition","《图画展览会》","Modest Mussorgsky","Fritz Reiner · Chicago Symphony",1957,"RCA","romantic",["管弦乐","独奏/键盘"],["管弦乐团"],["壮丽","激昂","专注"],"穆索尔斯基为纪念亡友的画展而作的钢琴组曲,经拉威尔配器成为炫目的管弦乐。从《牛车》到《基辅大门》,是展示乐队色彩的终极名片。莱纳与芝加哥交响华丽逼人。"],
["Symphony No. 2 'Resurrection'","《第二交响曲“复活”》","Gustav Mahler","Otto Klemperer · Philharmonia",1963,"EMI","romantic",["交响曲","合唱/宗教"],["管弦乐团","合唱","人声"],["壮丽","庄严","激昂"],"从葬礼进行曲到末乐章合唱‘你将复活’的巨大升腾,马勒用九十分钟叩问生死。克伦佩勒的演绎坚如磐石、崇高恢弘,是‘复活’交响曲最具重量感的丰碑。"],
["Symphony No. 5","《第五交响曲》","Gustav Mahler","Leonard Bernstein · Wiener Philharmoniker",1987,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["悲伤","激昂","亲密"],"第四乐章的‘小柔板’因电影《魂断威尼斯》而闻名于世——写给妻子阿尔玛的无言情书。伯恩斯坦是马勒最炽热的信徒,他的演绎全情投入,把生死爱欲燃烧殆尽。"],
["Das Lied von der Erde","《大地之歌》","Gustav Mahler","Bruno Walter · Kathleen Ferrier",1952,"Decca","romantic",["交响曲","声乐/艺术歌曲"],["管弦乐团","人声"],["悲伤","沉思","夜晚"],"马勒以唐诗为词写下的交响声乐套曲,在东方的诗意里凝视死亡与告别。末乐章《告别》重复的‘永远’令人肝肠寸断。费里尔与瓦尔特的这版是催人泪下的传奇。"],
["Symphony No. 9","《第九交响曲》","Gustav Mahler","Herbert von Karajan · Berliner Philharmoniker",1982,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["悲伤","沉思","庄严"],"马勒对尘世最后的告别,末乐章的弦乐在极弱中缓缓消散,如生命之火熄灭。卡拉扬1982年的现场录音被誉为他毕生最伟大的成就之一,静谧得令人窒息。"],
["La bohème","《波希米亚人》","Giacomo Puccini","Herbert von Karajan · Berliner Philharmoniker",1972,"Decca","romantic",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","亲密","夜晚"],"关于巴黎阁楼里贫穷艺术家与绣花女咪咪的爱情悲剧,普契尼最动人的旋律尽在其中。帕瓦罗蒂与弗蕾妮的演唱、卡拉扬的指挥,成就了公认最美的一版《波希米亚人》。"],
["Tosca","《托斯卡》","Giacomo Puccini","Victor de Sabata · Maria Callas",1953,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["激昂","悲伤","夜晚"],"歌剧录音史上的圣杯。卡拉斯化身歌唱家托斯卡,把爱情、谋杀与殉情演绎得惊心动魄;《为艺术,为爱情》一曲成绝唱。德·萨巴塔的指挥与之相得益彰,被公认为史上最伟大的歌剧录音。"],
["Four Last Songs","《最后四首歌》","Richard Strauss","Elisabeth Schwarzkopf · George Szell",1965,"EMI","romantic",["声乐/艺术歌曲","管弦乐"],["人声","管弦乐团"],["疗愈","悲伤","沉思"],"理查·施特劳斯八十四岁的告别之作,在晚霞般的管弦乐上从容凝视死亡。末句‘这就是死亡吗?’化入云雀般的长笛。施瓦茨科普夫的演唱温暖圆熟,是这部天鹅之歌的绝对经典。"],
["Also sprach Zarathustra","《查拉图斯特拉如是说》","Richard Strauss","Fritz Reiner · Chicago Symphony",1954,"RCA","romantic",["管弦乐"],["管弦乐团","管风琴"],["壮丽","庄严","激昂"],"因电影《2001太空漫游》而永载流行文化的开场——管风琴、定音鼓与铜管描绘日出的‘世界之谜’动机。莱纳与芝加哥交响1954年的录音是发烧友心中的试机天碟。"],
["Cello Concerto","《e小调大提琴协奏曲》","Edward Elgar","Jacqueline du Pré · John Barbirolli",1965,"EMI","romantic",["协奏曲"],["大提琴","管弦乐团"],["悲伤","沉思","疗愈"],"一战后弥漫着挽歌气息的杰作。二十岁的杜普蕾以近乎燃烧生命的投入演绎,把埃尔加的怀旧与哀伤化为琴弓下的呐喊。这个1965年的版本已成传奇,再无人能出其右。"],
["Symphony No. 2","《第二交响曲》","Jean Sibelius","Herbert von Karajan · Berliner Philharmoniker",1980,"EMI","romantic",["交响曲"],["管弦乐团"],["壮丽","激昂","庄严"],"芬兰的民族之声,终乐章从阴郁挣扎走向D大调的辉煌胜利,常被视为民族独立的象征。西贝柳斯把北欧的冷峻与炽热熔于一炉,卡拉扬的演绎大开大合,气象恢弘。"],
["Piano Concerto No. 2","《第二钢琴协奏曲》","Sergei Rachmaninoff","Sviatoslav Richter · Stanisław Wisłocki",1959,"Deutsche Grammophon","romantic",["协奏曲"],["钢琴","管弦乐团"],["悲伤","激昂","亲密","夜晚"],"最受欢迎的钢琴协奏曲,拉赫玛尼诺夫从抑郁症中走出后写下的浓情巨作,旋律绵长如江河。里希特深沉厚重的演绎把俄罗斯式的忧郁与激情推向极致。"],
["Piano Concerto No. 3","《第三钢琴协奏曲》","Sergei Rachmaninoff","Vladimir Horowitz · Eugene Ormandy",1978,"RCA","romantic",["协奏曲"],["钢琴","管弦乐团"],["激昂","壮丽","悲伤"],"被称为‘世界上最难的钢琴协奏曲’,因电影《闪亮的风采》广为人知。霍洛维茨是这部作品的化身——拉赫玛尼诺夫本人都称赞他弹得比自己更好,这版现场惊心动魄。"],
// 现代
["La mer / Prélude à l'après-midi d'un faune","《大海 · 牧神午后》","Claude Debussy","Herbert von Karajan · Berliner Philharmoniker",1964,"Deutsche Grammophon","modern",["管弦乐"],["管弦乐团"],["沉思","夜晚","疗愈"],"印象主义的旗帜。德彪西以模糊的调性、闪烁的音色描绘光影与水波,《牧神午后》的长笛开篇被视为现代音乐的起点。卡拉扬的演绎色彩斑斓、雾气氤氲。"],
["Préludes (Books 1 & 2)","《前奏曲集》","Claude Debussy","Krystian Zimerman",1994,"Deutsche Grammophon","modern",["独奏/键盘"],["钢琴"],["沉思","夜晚","亲密"],"二十四首钢琴前奏曲,每首都是一幅微型画:沉没的教堂、雪上足迹、亚麻色头发的少女。德彪西解放了钢琴的音色,齐默尔曼的演绎精致入微、意境悠远。"],
["Boléro / Daphnis et Chloé","《波莱罗 · 达夫尼斯与克洛埃》","Maurice Ravel","Charles Munch · Boston Symphony",1955,"RCA","modern",["管弦乐","芭蕾"],["管弦乐团"],["激昂","壮丽","专注"],"《波莱罗》用一个不断重复的旋律与永恒的小鼓,在十五分钟内堆积成排山倒海的高潮——一场配器的魔术。拉威尔是‘瑞士钟表匠’般的管弦乐大师,明希演来精准而奔放。"],
["Piano Concerto in G","《G大调钢琴协奏曲》","Maurice Ravel","Arturo Benedetti Michelangeli · Ettore Gracis",1957,"EMI","modern",["协奏曲"],["钢琴","管弦乐团"],["喜悦","亲密","夜晚"],"融合了爵士的俏皮与莫扎特式的优雅,第二乐章开篇长达数分钟的钢琴独白是二十世纪最美的柔板之一。米开朗杰利的演绎晶莹剔透、无懈可击。"],
["The Rite of Spring","《春之祭》","Igor Stravinsky","Igor Stravinsky · Columbia Symphony",1960,"Columbia","modern",["管弦乐","芭蕾"],["管弦乐团","打击乐"],["激昂","壮丽","专注"],"1913年首演引发骚乱的作品,原始的节奏冲击与狂暴的和声撕裂了西方音乐的调性传统,被视为二十世纪音乐的分水岭。作曲家亲自指挥,权威性无可置疑。"],
["Petrushka / The Firebird","《彼得鲁什卡 · 火鸟》","Igor Stravinsky","Pierre Boulez · New York Philharmonic",1971,"Columbia","modern",["管弦乐","芭蕾"],["管弦乐团"],["激昂","喜悦","壮丽"],"斯特拉文斯基为佳吉列夫俄罗斯芭蕾舞团写的两部早期杰作,色彩绚烂、节奏鲜活。布列兹以分析家的冷静与精确梳理出斯特拉文斯基复杂的织体,清晰锐利。"],
["Concerto for Orchestra","《乐队协奏曲》","Béla Bartók","Fritz Reiner · Chicago Symphony",1955,"RCA","modern",["管弦乐"],["管弦乐团"],["激昂","壮丽","专注"],"巴托克流亡美国、贫病交加时写下的杰作,让整个乐队轮番担任独奏‘炫技’。既有民间舞曲的活力,也有夜之音乐的神秘。莱纳与芝加哥交响的演绎锋芒毕露,堪称范本。"],
["String Quartets (Complete)","《弦乐四重奏全集》","Béla Bartók","Emerson String Quartet",1988,"Deutsche Grammophon","modern",["室内乐"],["弦乐四重奏"],["激昂","沉思","专注"],"贝多芬之后弦乐四重奏最重要的里程碑,六部作品浓缩了巴托克的全部语言:民间音乐、夜之音乐、尖锐的不协和与严密的结构。爱默生四重奏的演绎凌厉精准。"],
["Romeo and Juliet","《罗密欧与朱丽叶》","Sergei Prokofiev","Lorin Maazel · Cleveland Orchestra",1973,"Decca","modern",["芭蕾","管弦乐"],["管弦乐团"],["悲伤","激昂","壮丽"],"二十世纪最伟大的芭蕾音乐之一。《骑士之舞》那阴森庄严的主题因广告与影视广为人知。普罗科菲耶夫把莎剧的爱与恨写成惊心动魄的管弦乐,马泽尔演绎得辉煌有力。"],
["Piano Concerto No. 3","《第三钢琴协奏曲》","Sergei Prokofiev","Martha Argerich · Claudio Abbado",1967,"Deutsche Grammophon","modern",["协奏曲"],["钢琴","管弦乐团"],["激昂","喜悦","专注"],"二十世纪最受欢迎的钢琴协奏曲,兼具钢铁般的节奏动力与抒情的俄罗斯旋律。二十六岁的阿格里奇一鸣惊人,与阿巴多合作的这版充满青春的锐气与火花。"],
["Symphony No. 5","《第五交响曲》","Dmitri Shostakovich","Leonard Bernstein · New York Philharmonic",1959,"Columbia","modern",["交响曲"],["管弦乐团"],["激昂","悲伤","壮丽"],"在斯大林的高压批判下写成的‘一个苏联艺术家对正当批评的答复’。终乐章那震耳欲聋的胜利究竟是真心还是反讽?伯恩斯坦的演绎充满张力,把这层暧昧演绎得惊心动魄。"],
["String Quartet No. 8","《第八弦乐四重奏》","Dmitri Shostakovich","Borodin Quartet",1962,"Melodiya","modern",["室内乐"],["弦乐四重奏"],["悲伤","夜晚","沉思"],"作曲家献给‘法西斯主义与战争受害者’、实为自我墓志铭的作品,通篇萦绕着他名字的音乐签名DSCH。鲍罗丁四重奏的演绎冷峻而痛彻心扉,是理解肖斯塔科维奇的钥匙。"],
["Symphony No. 10","《第十交响曲》","Dmitri Shostakovich","Herbert von Karajan · Berliner Philharmoniker",1966,"Deutsche Grammophon","modern",["交响曲"],["管弦乐团"],["激昂","悲伤","壮丽"],"斯大林死后写下的杰作,第二乐章据说是暴君的音乐肖像——狂暴而短促。卡拉扬罕见地钟爱这部当代作品并两度录音,柏林爱乐的演绎精悍强劲,张力十足。"],
["Verklärte Nacht","《升华之夜》","Arnold Schoenberg","Herbert von Karajan · Berliner Philharmoniker",1974,"Deutsche Grammophon","modern",["室内乐","管弦乐"],["弦乐四重奏","管弦乐团"],["夜晚","沉思","悲伤"],"勋伯格走向无调性之前的晚期浪漫杰作,为弦乐写就的一首炽热的夜之情诗。旋律仍缠绵可听,却已在半音的暗流中悸动。卡拉扬的弦乐如天鹅绒般浓稠动人。"],
["Violin Concerto 'To the Memory of an Angel'","《小提琴协奏曲“纪念一位天使”》","Alban Berg","Itzhak Perlman · Seiji Ozawa",1978,"Deutsche Grammophon","modern",["协奏曲"],["小提琴","管弦乐团"],["悲伤","沉思","疗愈"],"为早逝的少女而作的安魂曲,贝尔格把十二音技法与巴赫的众赞歌、维也纳圆舞曲交织,让先锋语言流淌出无尽的温柔与哀恸。帕尔曼的演绎凄美动人,催人泪下。"],
["War Requiem","《战争安魂曲》","Benjamin Britten","Benjamin Britten · London Symphony",1963,"Decca","modern",["合唱/宗教","声乐"],["合唱","管弦乐团","人声"],["悲伤","庄严","沉思"],"为重建被炸毁的考文垂大教堂而作,布里顿把拉丁安魂弥撒与一战诗人欧文的反战诗篇并置,发出震撼人心的和平呼喊。作曲家亲自指挥的首演录音,是二十世纪的良心之声。"],
["Appalachian Spring","《阿巴拉契亚之春》","Aaron Copland","Aaron Copland · London Symphony",1970,"Columbia","modern",["管弦乐","芭蕾"],["管弦乐团"],["疗愈","喜悦","沉思"],"美国声音的化身。科普兰以开阔明朗的和声描绘拓荒者的婚礼,结尾对震颤派赞美诗《简单的礼物》的变奏宁静而崇高。作曲家亲自指挥,亲切而权威。"],
["Rhapsody in Blue","《蓝色狂想曲》","George Gershwin","Leonard Bernstein · Columbia Symphony",1959,"Columbia","modern",["管弦乐","协奏曲"],["钢琴","管弦乐团","单簧管"],["喜悦","激昂","夜晚"],"爵士与古典的完美联姻。开篇单簧管那声慵懒的滑音是二十世纪美国音乐最著名的开场。伯恩斯坦身兼钢琴与指挥,把纽约的喧嚣与浪漫演绎得酣畅淋漓。"],
["Carmina Burana","《布兰诗歌》","Carl Orff","Eugen Jochum · Berlin Deutsche Oper",1968,"Deutsche Grammophon","modern",["合唱/宗教","声乐"],["合唱","管弦乐团","打击乐"],["壮丽","激昂","庄严"],"开场与结尾的《哦,命运女神》因无数电影广告而家喻户晓。奥尔夫用原始有力的节奏与中世纪诗歌唤起对命运之轮的敬畏。约胡姆的演绎经作曲家亲自认可,气势磅礴。"],
["Quatuor pour la fin du temps","《为时间终结而作的四重奏》","Olivier Messiaen","Tashi Ensemble",1976,"RCA","modern",["室内乐"],["单簧管","小提琴","大提琴","钢琴"],["沉思","悲伤","疗愈"],"梅西安在纳粹战俘营里为营中仅有的乐器写就、并在零下严寒中首演的杰作。他把对上帝、鸟鸣与永恒的信仰写进这部超越时间的室内乐,神秘而崇高。"],
["Turangalîla-Symphonie","《图伦加利拉交响曲》","Olivier Messiaen","André Previn · London Symphony",1978,"EMI","modern",["交响曲","管弦乐"],["管弦乐团","钢琴"],["壮丽","激昂","喜悦"],"一部关于爱与狂喜的巨大交响曲,用上电子乐器马特诺琴发出的销魂颤音。梅西安把印度节奏、鸟鸣与感官的极乐熔铸成十乐章的宇宙盛宴,色彩绚烂夺目。"],
// 当代
["Symphony No. 3 'Symphony of Sorrowful Songs'","《第三交响曲“悲歌交响曲”》","Henryk Górecki","Dawn Upshaw · David Zinman",1992,"Nonesuch","contemporary",["交响曲","声乐/艺术歌曲"],["管弦乐团","人声"],["悲伤","疗愈","沉思"],"神圣极简主义的奇迹。三个缓慢的乐章围绕母亲与孩子的离别之痛,其中一段歌词是奥斯维辛牢房墙上的少女祷文。这张1992年的唱片意外登上流行榜,售出百万,抚慰了无数心灵。"],
["Tabula Rasa","《白板》","Arvo Pärt","Gidon Kremer · Keith Jarrett · Dennis Russell Davies",1984,"ECM New Series","contemporary",["室内乐","协奏曲"],["小提琴","钢琴","管弦乐团"],["沉思","疗愈","悲伤","亲密"],"佩尔特‘钟鸣作曲法’的巅峰,音乐澄澈如水晶、静谧如祈祷。这张开启ECM新系列的唱片重新定义了当代古典的听感——极简、神圣、直抵人心。基顿·克莱默的小提琴纯净通透。"],
["Music for 18 Musicians","《为18位音乐家而作的音乐》","Steve Reich","Steve Reich and Musicians",1978,"ECM New Series","contemporary",["室内乐"],["打击乐","钢琴","单簧管","人声"],["专注","疗愈","喜悦"],"简约主义的里程碑。持续脉动的马林巴、钢琴与人声在近一小时里缓缓相位偏移、渐变循环,像呼吸一样起伏。赖希亲自率团的这版是简约音乐最迷人的入门。"],
["Glassworks","《玻璃作品》","Philip Glass","Philip Glass Ensemble",1982,"CBS","contemporary",["室内乐"],["钢琴","管弦乐团"],["专注","夜晚","沉思"],"格拉斯写给随身听时代的简约音乐,琶音如齿轮般不停转动、层层叠加。作为进入他浩瀚宇宙(歌剧、电影配乐)的门径,《玻璃作品》亲切、催眠而美丽。"],
["Shaker Loops / Harmonium","《颤木环 · 和声》","John Adams","Edo de Waart · San Francisco Symphony",1984,"ECM / Nonesuch","contemporary",["管弦乐","合唱/宗教"],["管弦乐团","合唱"],["激昂","壮丽","专注"],"后简约主义的代表。约翰·亚当斯在赖希、格拉斯的脉动之上,重新注入浪漫主义的情感与交响的宏大。《颤木环》的弦乐颤动如能量涌流,充满美式的乐观与光辉。"],
["Études","《钢琴练习曲》","György Ligeti","Pierre-Laurent Aimard",1996,"Sony / Warner","contemporary",["独奏/键盘"],["钢琴"],["激昂","专注","壮丽"],"二十世纪末最重要的钢琴练习曲,把非洲复节奏、分形几何与钢琴的极限技巧熔于一炉,狂放而精密。艾马尔的演绎令人瞠目结舌,是当代钢琴文献的高峰。"],
["Threnody to the Victims of Hiroshima","《广岛受难者挽歌》","Krzysztof Penderecki","Krzysztof Penderecki · Polish Radio",1961,"EMI","contemporary",["管弦乐"],["管弦乐团"],["悲伤","激昂","沉思"],"五十二件弦乐器发出刺耳的音簇、滑音与敲击,把核爆的恐怖化为纯粹的声音。潘德列茨基以先锋的‘音响主义’写下这部震撼的挽歌,是二十世纪最令人难忘的抗议之声。"]
];

// ---- 第二批扩充（同为公认标杆/传奇录音）----
const R2 = [
// 巴洛克 扩充
["St John Passion","《约翰受难曲》","Johann Sebastian Bach","John Eliot Gardiner · Monteverdi Choir",1986,"Archiv","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团"],["悲伤","庄严","沉思"],"较《马太》更紧凑、更戏剧化的受难叙事，开篇合唱如汹涌浪潮。加德纳的本真演绎充满动能，把巴赫的悲悯与张力和盘托出。"],
["Christmas Oratorio","《圣诞清唱剧》","Johann Sebastian Bach","John Eliot Gardiner · English Baroque Soloists",1987,"Archiv","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团","小号"],["喜悦","庄严","壮丽"],"六部康塔塔串成的圣诞欢庆，开篇定音鼓与小号的合唱《欢呼吧，雀跃吧》喜气盈盈。加德纳的演绎明亮灵动，是节日里最温暖的巴赫。"],
["Orchestral Suites","《管弦乐组曲》","Johann Sebastian Bach","Trevor Pinnock · The English Concert",1979,"Archiv","baroque",["管弦乐"],["管弦乐团","长笛","小号"],["喜悦","专注","庄严"],"四套组曲里藏着著名的《G弦上的咏叹调》与欢快的《嬉游曲》。品诺克的本真演奏轻盈典雅，展现巴赫世俗音乐里明快优美的一面。"],
["Keyboard Concertos","《键盘协奏曲》","Johann Sebastian Bach","Murray Perahia · Academy of St Martin",2001,"Sony","baroque",["协奏曲","独奏/键盘"],["钢琴","管弦乐团"],["专注","喜悦","亲密"],"史上第一批为键盘乐器写的协奏曲。佩拉希亚以现代钢琴演绎兼指挥，触键温润如歌，把巴赫的对位织体弹得清澈流畅。"],
["Toccata & Fugue / Organ Works","《托卡塔与赋格 · 管风琴作品》","Johann Sebastian Bach","Helmut Walcha",1963,"Archiv","baroque",["独奏/键盘"],["管风琴"],["壮丽","庄严","激昂"],"d小调《托卡塔与赋格》那开篇的下行音型是古典音乐最著名的旋律之一。双目失明的瓦尔哈凭记忆录下巴赫全部管风琴作品，庄严恢弘、结构如大教堂。"],
["The Art of Fugue","《赋格的艺术》","Johann Sebastian Bach","Musica Antiqua Köln · Reinhard Goebel",1984,"Archiv","baroque",["室内乐"],["弦乐四重奏","羽管键琴"],["专注","沉思","庄严"],"巴赫临终前对赋格技艺的终极探索，同一主题演化出十四段赋格与四首卡农，写到最后一段戛然而止。理性与神秘并存，是纯粹音乐思维的最高结晶。"],
["Cantatas BWV 140 & 147","《康塔塔 140 · 147》","Johann Sebastian Bach","Karl Richter · Münchener Bach-Chor",1978,"Archiv","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团"],["疗愈","庄严","喜悦"],"《醒来吧》与《耶稣，世人仰望的喜悦》——巴赫两百多部教堂康塔塔里最动人的两首，后者的众赞歌旋律家喻户晓。里希特的演绎虔诚庄重。"],
["Giulio Cesare","《朱利奥·凯撒》","George Frideric Handel","René Jacobs · Concerto Köln",1991,"Harmonia Mundi","baroque",["歌剧","声乐"],["人声","管弦乐团"],["壮丽","激昂","亲密"],"亨德尔正歌剧的巅峰，凯撒与克莱奥帕特拉的咏叹调华丽炫技。雅各布斯的本真演绎生动鲜活，让这门一度沉寂的‘返始咏叹调’艺术重焕光彩。"],
["Concerti Grossi Op. 6","《大协奏曲，作品6》","George Frideric Handel","Trevor Pinnock · The English Concert",1984,"Archiv","baroque",["协奏曲","管弦乐"],["管弦乐团"],["喜悦","壮丽","专注"],"与巴赫《勃兰登堡》并称的巴洛克大协奏曲高峰，十二首各具个性、旋律高贵。品诺克的演绎优雅从容，是亨德尔器乐的代表作。"],
["Coronation Anthems","《加冕颂歌》","George Frideric Handel","Simon Preston · Trevor Pinnock",1982,"Archiv","baroque",["合唱/宗教"],["合唱","管弦乐团","小号"],["壮丽","庄严","喜悦"],"《祭司撒督》自1727年乔治二世加冕起，历次英王加冕沿用至今。开篇弦乐的层层铺垫后合唱轰然而入，是最激动人心的庆典音乐之一。"],
["Gloria in D","《荣耀经》","Antonio Vivaldi","Robert King · The King's Consort",1988,"Hyperion","baroque",["合唱/宗教","声乐"],["合唱","管弦乐团"],["喜悦","壮丽","庄严"],"维瓦尔第最著名的合唱杰作，开篇的《荣耀归主》以跳跃的八度充满节日的欢腾。旋律明快、结构精巧，是巴洛克宗教音乐里最讨喜的一部。"],
["L'estro armonico Op. 3","《和声的灵感》","Antonio Vivaldi","Trevor Pinnock · The English Concert",1980,"Archiv","baroque",["协奏曲"],["小提琴","管弦乐团"],["喜悦","激昂","专注"],"维瓦尔第风靡全欧的协奏曲集，连巴赫都改编了其中数首。快板的活力与慢板的如歌确立了独奏协奏曲的范式，品诺克演来朝气蓬勃。"],
["Concerti Grossi Op. 6","《大协奏曲，作品6》","Arcangelo Corelli","The English Concert · Trevor Pinnock",1988,"Archiv","baroque",["协奏曲","管弦乐"],["管弦乐团"],["庄严","专注","疗愈"],"大协奏曲这一体裁的奠基之作，其中《圣诞协奏曲》宁静优美、流传至今。科雷利的旋律纯净均衡，是整个巴洛克器乐语言的源头之一。"],
["Tafelmusik","《餐桌音乐》","Georg Philipp Telemann","Musica Antiqua Köln · Reinhard Goebel",1988,"Archiv","baroque",["室内乐","管弦乐"],["管弦乐团","长笛"],["喜悦","专注","亲密"],"泰勒曼为贵族宴饮而编的大型器乐集，融合法国、意大利风格，优雅而多变。戈贝尔的锐利演绎证明这位巴洛克最高产的作曲家绝非泛泛。"],
["Pièces de clavecin en concerts","《羽管键琴合奏曲》","Jean-Philippe Rameau","William Christie · Les Arts Florissants",1990,"Harmonia Mundi","baroque",["室内乐","独奏/键盘"],["羽管键琴"],["亲密","喜悦","专注"],"法国巴洛克的集大成者，和声大胆、色彩细腻。克里斯蒂的演绎典雅生动，让拉莫笔下精巧的舞曲与人物素描栩栩如生。"],
["Canon and Gigue in D","《D大调卡农与吉格》","Johann Pachelbel","Jean-François Paillard Chamber Orchestra",1968,"Erato","baroque",["室内乐"],["弦乐四重奏","管弦乐团"],["疗愈","亲密","庄严"],"世界上最著名的婚礼音乐——三把小提琴在固定低音上层层叠加的卡农。帕亚尔1968年的这版让这首沉睡的小品红遍全球。"],
["Adagio in G minor","《g小调柔板》","Tomaso Albinoni","I Musici",1968,"Philips","baroque",["室内乐","管弦乐"],["弦乐四重奏","管风琴"],["悲伤","沉思","疗愈"],"如泣如诉的弦乐柔板，常现于电影与葬礼（实为后人贾佐托据残稿写成）。忧郁高贵的旋律让阿尔比诺尼之名家喻户晓，是最催泪的巴洛克名曲。"],
["The Fairy Queen","《仙后》","Henry Purcell","John Eliot Gardiner · English Baroque Soloists",1981,"Archiv","baroque",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","亲密","壮丽"],"珀塞尔取材莎剧《仲夏夜之梦》的半歌剧，舞曲、咏叹与合唱缤纷多姿。加德纳的演绎鲜活灵动，尽显英国巴洛克舞台音乐的斑斓色彩。"],
// 古典主义 扩充
["Orfeo ed Euridice","《奥菲欧与尤丽狄茜》","Christoph Willibald Gluck","John Eliot Gardiner · English Baroque Soloists",1989,"Philips","classical",["歌剧","声乐"],["人声","合唱","管弦乐团"],["悲伤","庄严","亲密"],"格鲁克‘歌剧改革’的旗帜，摒弃炫技、追求真挚。奥菲欧痛失爱妻后的咏叹《我失去了尤丽狄茜》质朴动人，为莫扎特之路铺就了基石。"],
["Trumpet Concerto","《降E大调小号协奏曲》","Joseph Haydn","Wynton Marsalis · Raymond Leppard",1983,"CBS","classical",["协奏曲"],["小号","管弦乐团"],["喜悦","壮丽","激昂"],"为新发明的键控小号而作，第三乐章活泼灿烂，是小号手的必修名片。爵士与古典双栖的马萨利斯以无瑕的技术与光泽演绎，一鸣惊人。"],
["Cello Concertos","《大提琴协奏曲》","Joseph Haydn","Mstislav Rostropovich · Academy of St Martin",1975,"EMI","classical",["协奏曲"],["大提琴","管弦乐团"],["喜悦","亲密","专注"],"C大调与D大调两部协奏曲优雅明快，是大提琴古典曲目的基石。罗斯特罗波维奇的演绎气度雍容、歌唱性十足。"],
["String Quartets Op. 76","《弦乐四重奏，作品76》","Joseph Haydn","Tokyo String Quartet",1993,"RCA","classical",["室内乐"],["弦乐四重奏"],["喜悦","专注","亲密"],"‘弦乐四重奏之父’晚期的巅峰，包含旋律化为德奥国歌的《皇帝》四重奏。海顿在此把四件乐器的对话写得机智而深情，东京四重奏演绎精致均衡。"],
["Così fan tutte","《女人心》","Wolfgang Amadeus Mozart","Karl Böhm · Philharmonia Orchestra",1962,"EMI","classical",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","亲密","沉思"],"莫扎特与达·蓬特合作的第三部喜歌剧，一则关于爱情忠诚的苦涩玩笑，重唱之美冠绝歌剧史。伯姆与施瓦茨科普夫等名角的这版温暖典雅。"],
["Symphonies Nos. 38 & 39","《第38“布拉格” · 39交响曲》","Wolfgang Amadeus Mozart","Karl Böhm · Berliner Philharmoniker",1966,"Deutsche Grammophon","classical",["交响曲"],["管弦乐团"],["喜悦","激昂","壮丽"],"晚期交响曲的门槛之作：‘布拉格’的戏剧张力与第39号的从容优雅。伯姆与柏林爱乐的演绎温润大气，古典风范十足。"],
["Piano Concertos Nos. 23 & 24","《第23 · 24钢琴协奏曲》","Wolfgang Amadeus Mozart","Murray Perahia · English Chamber Orchestra",1984,"CBS","classical",["协奏曲"],["钢琴","管弦乐团"],["亲密","悲伤","喜悦"],"A大调（第23号）柔板的孤独之美与c小调（第24号）的悲剧深度。佩拉希亚身兼独奏与指挥，触键如珍珠般圆润，是公认最诗意的莫扎特协奏曲全集之一。"],
["Great Mass in C minor","《c小调大弥撒》","Wolfgang Amadeus Mozart","John Eliot Gardiner · Monteverdi Choir",1987,"Philips","classical",["合唱/宗教","声乐"],["合唱","管弦乐团"],["庄严","壮丽","疗愈"],"莫扎特未完成的宏伟弥撒，《垂怜经》的女高音独唱美得令人屏息。加德纳的演绎兼具巴洛克的辉煌与古典的均衡，是这部残篇最动人的呈现。"],
["Horn Concertos","《圆号协奏曲》","Wolfgang Amadeus Mozart","Dennis Brain · Herbert von Karajan",1953,"EMI","classical",["协奏曲"],["管弦乐团"],["喜悦","亲密","专注"],"圆号曲目的圣经，旋律明朗、诙谐幽默。英年早逝的传奇圆号家丹尼斯·布莱恩音色温暖、乐句如歌，这版1953年录音至今无人超越。"],
["Clarinet Quintet","《单簧管五重奏》","Wolfgang Amadeus Mozart","Jack Brymer · Allegri Quartet",1963,"EMI","classical",["室内乐"],["单簧管","弦乐四重奏"],["亲密","疗愈","沉思"],"单簧管与弦乐四重奏交融出的温柔杰作，与《单簧管协奏曲》同为莫扎特对这件乐器的情书。布莱默的音色圆润如天鹅绒，慢乐章宁静动人。"],
["Piano Concerto No. 5 'Emperor'","《第五钢琴协奏曲“皇帝”》","Ludwig van Beethoven","Emil Gilels · George Szell",1968,"EMI","classical",["协奏曲"],["钢琴","管弦乐团"],["壮丽","激昂","庄严"],"最宏伟的钢琴协奏曲之一，开篇即由钢琴的华彩宣告帝王气度，慢乐章则崇高静谧。吉列尔斯钢铁般的力量与塞尔的严整乐队相得益彰。"],
["Triple Concerto","《三重协奏曲》","Ludwig van Beethoven","Oistrakh · Rostropovich · Richter · Karajan",1969,"EMI","classical",["协奏曲"],["小提琴","大提琴","钢琴","管弦乐团"],["壮丽","喜悦","亲密"],"为钢琴、小提琴、大提琴与乐队而作的独特协奏曲。奥伊斯特拉赫、罗斯特罗波维奇、里希特三大巨匠加卡拉扬的柏林爱乐——史上最豪华的‘梦之队’阵容。"],
["Symphony No. 3 'Eroica'","《第三交响曲“英雄”》","Ludwig van Beethoven","Otto Klemperer · Philharmonia Orchestra",1959,"EMI","classical",["交响曲"],["管弦乐团"],["壮丽","激昂","庄严"],"交响曲史的分水岭——贝多芬以它把交响曲从娱乐扩展为英雄的史诗，原题献拿破仑，闻其称帝后愤而涂去。克伦佩勒的演绎坚如磐石、气象恢弘。"],
["Symphony No. 6 'Pastoral'","《第六交响曲“田园”》","Ludwig van Beethoven","Bruno Walter · Columbia Symphony",1958,"Columbia","classical",["交响曲"],["管弦乐团"],["疗愈","喜悦","沉思"],"贝多芬对大自然的深情礼赞，从溪畔漫步到暴风雨后的感恩。瓦尔特晚年的这版温暖从容、呼吸自然，是‘田园’交响曲最亲切的诠释。"],
["Piano Trio 'Archduke'","《大公三重奏》","Ludwig van Beethoven","Beaux Arts Trio",1979,"Philips","classical",["室内乐"],["钢琴","小提琴","大提琴"],["亲密","庄严","沉思"],"钢琴三重奏文献的巅峰，题献鲁道夫大公，气度宽广、慢乐章崇高如赞美诗。美艺三重奏的演绎均衡默契，是室内乐的典范。"],
["Missa Solemnis","《庄严弥撒》","Ludwig van Beethoven","Otto Klemperer · New Philharmonia",1966,"EMI","classical",["合唱/宗教","声乐"],["合唱","管弦乐团"],["庄严","壮丽","沉思"],"贝多芬自认最伟大的作品，一部超越教派的信仰宣言，谱首题着‘发自内心——但愿能抵达内心’。克伦佩勒的演绎崇高厚重，与《贝九》比肩。"],
["Fidelio","《费德里奥》","Ludwig van Beethoven","Otto Klemperer · Philharmonia Orchestra",1962,"EMI","classical",["歌剧","声乐"],["人声","合唱","管弦乐团"],["激昂","壮丽","庄严"],"贝多芬唯一的歌剧，一曲关于自由、忠贞与反抗暴政的颂歌。囚徒们步出地牢重见天日的合唱感人至深。克伦佩勒的演绎庄严崇高，理想主义光芒四射。"],
// 浪漫主义 扩充
["Symphony No. 8 'Unfinished'","《第八交响曲“未完成”》","Franz Schubert","Carlos Kleiber · Wiener Philharmoniker",1978,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["悲伤","沉思","夜晚"],"只有两个乐章却完满自足的谜之杰作，开篇低音的幽暗动机笼罩全曲。小克莱伯的演绎充满戏剧张力与歌唱性，是‘未完成’最迷人的版本之一。"],
["Trout Quintet","《鳟鱼五重奏》","Franz Schubert","Clifford Curzon · Vienna Octet Members",1958,"Decca","romantic",["室内乐"],["钢琴","小提琴","大提琴"],["喜悦","疗愈","亲密"],"以舒伯特歌曲《鳟鱼》为主题变奏的第四乐章明媚欢快，是最讨人喜爱的室内乐。柯曾与维也纳八重奏成员的演绎清新流畅，如溪水潺潺。"],
["String Quartet 'Death and the Maiden'","《死神与少女四重奏》","Franz Schubert","Alban Berg Quartett",1984,"EMI","romantic",["室内乐"],["弦乐四重奏"],["悲伤","激昂","夜晚"],"以歌曲《死神与少女》为主题的d小调四重奏，从第一个和弦起便被死亡的阴影笼罩。阿尔班·贝尔格四重奏的演绎凌厉而深沉，惊心动魄。"],
["Die schöne Müllerin","《美丽的磨坊女》","Franz Schubert","Fritz Wunderlich · Hubert Giesen",1966,"Deutsche Grammophon","romantic",["声乐/艺术歌曲"],["人声","钢琴"],["亲密","悲伤","疗愈"],"青年磨工在溪畔的爱情与幻灭，二十首歌串成清新又心碎的旅程。天才男高音翁德里希在录后不久意外早逝，这份纯净明亮的歌声成为永恒的绝唱。"],
["Dichterliebe","《诗人之恋》","Robert Schumann","Fritz Wunderlich · Hubert Giesen",1965,"Deutsche Grammophon","romantic",["声乐/艺术歌曲"],["人声","钢琴"],["悲伤","亲密","夜晚"],"以海涅诗作谱成的十六首爱情套曲，钢琴的尾奏常比歌声更幽深。翁德里希温暖通透的男高音，把浪漫主义的甜蜜与苦涩演绎得动人心弦。"],
["Cello Concerto","《a小调大提琴协奏曲》","Robert Schumann","Jacqueline du Pré · Daniel Barenboim",1968,"EMI","romantic",["协奏曲"],["大提琴","管弦乐团"],["悲伤","亲密","沉思"],"三个乐章一气呵成、内省而抒情的杰作。杜普蕾以其标志性的炽热投入演绎，与丈夫巴伦博伊姆的乐队交融无间，深情动人。"],
["Symphony No. 4 'Italian'","《第四交响曲“意大利”》","Felix Mendelssohn","Claudio Abbado · London Symphony",1984,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["喜悦","激昂","壮丽"],"门德尔松游历意大利的阳光结晶，开篇跳跃的旋律洋溢南国的明媚。阿巴多的演绎轻盈灿烂，是浪漫主义中最令人愉悦的交响曲之一。"],
["Études, Opp. 10 & 25","《练习曲，作品10 · 25》","Frédéric Chopin","Maurizio Pollini",1972,"Deutsche Grammophon","romantic",["独奏/键盘"],["钢琴"],["激昂","专注","壮丽"],"把钢琴技巧升华为诗与艺术的二十四首练习曲，从《革命》到《离别》各具灵魂。波利尼1972年的这版技术无懈可击、气势磅礴，被奉为不可逾越的标杆。"],
["Piano Concertos Nos. 1 & 2","《第一 · 第二钢琴协奏曲》","Frédéric Chopin","Krystian Zimerman · Polish Festival Orchestra",1999,"Deutsche Grammophon","romantic",["协奏曲"],["钢琴","管弦乐团"],["亲密","悲伤","激昂"],"青年肖邦的青春告白，慢乐章如月夜下的夜曲般缠绵。齐默尔曼亲自组建乐团、身兼指挥，倾力打磨出这版精雕细琢、诗意盎然的经典。"],
["Waltzes","《圆舞曲》","Frédéric Chopin","Dinu Lipatti",1950,"EMI","romantic",["独奏/键盘"],["钢琴"],["亲密","喜悦","夜晚"],"肖邦的圆舞曲兼具沙龙的优雅与内心的私语。天才钢琴家利帕蒂在病逝前录下的这版清澈脱俗、分寸完美，是唱片史上的不朽名盘。"],
["Polonaises","《波洛涅兹舞曲》","Frédéric Chopin","Arthur Rubinstein",1964,"RCA","romantic",["独奏/键盘"],["钢琴"],["壮丽","激昂","庄严"],"肖邦民族气节的化身，《英雄》波洛涅兹以铿锵的节奏呼唤波兰的荣光。鲁宾斯坦高贵而不失火焰的演绎，被公认为波洛涅兹的正统。"],
["Piano Concertos Nos. 1 & 2","《第一 · 第二钢琴协奏曲》","Franz Liszt","Sviatoslav Richter · Kirill Kondrashin",1961,"Philips","romantic",["协奏曲"],["钢琴","管弦乐团"],["激昂","壮丽","喜悦"],"李斯特把炫技与交响思维熔于一炉的两部协奏曲，第一号以三角铁的清脆闻名。里希特雷霆万钧的演绎与孔德拉辛的乐队火花四溅，酣畅淋漓。"],
["Années de pèlerinage","《巡礼之年》","Franz Liszt","Lazar Berman",1977,"Deutsche Grammophon","romantic",["独奏/键盘"],["钢琴"],["沉思","亲密","壮丽"],"李斯特以音乐记录旅途见闻与阅读感悟的钢琴日记，《艾斯特庄园的喷泉》波光粼粼。俄国巨匠贝尔曼的演绎气势恢弘又饱含诗意，是这套巨作的经典诠释。"],
["Symphony No. 1","《第一交响曲》","Johannes Brahms","Otto Klemperer · Philharmonia Orchestra",1957,"EMI","romantic",["交响曲"],["管弦乐团"],["庄严","激昂","壮丽"],"勃拉姆斯酝酿二十余年、被誉为‘贝多芬第十’的处女交响曲，终乐章的宽广主题致敬《欢乐颂》。克伦佩勒的演绎厚重坚实、结构如岩石般稳固。"],
["Piano Concerto No. 1","《第一钢琴协奏曲》","Johannes Brahms","Emil Gilels · Eugen Jochum",1972,"Deutsche Grammophon","romantic",["协奏曲"],["钢琴","管弦乐团"],["激昂","悲伤","壮丽"],"交响性厚重、充满青年勃拉姆斯风暴般激情的巨作，开篇乐队的轰鸣震撼人心。吉列尔斯与约胡姆的合作大气磅礴、深沉有力，是公认的权威版本。"],
["Piano Concerto No. 2","《第二钢琴协奏曲》","Johannes Brahms","Sviatoslav Richter · Erich Leinsdorf",1960,"RCA","romantic",["协奏曲"],["钢琴","管弦乐团"],["壮丽","庄严","亲密"],"四个乐章、宛如为钢琴与乐队而作的交响曲，第三乐章有大提琴的绝美独白。里希特的演绎力量与诗意兼具，展现勃拉姆斯晚期的从容与深邃。"],
["Double Concerto","《小提琴与大提琴二重协奏曲》","Johannes Brahms","Oistrakh · Rostropovich · George Szell",1969,"EMI","romantic",["协奏曲"],["小提琴","大提琴","管弦乐团"],["庄严","激昂","亲密"],"勃拉姆斯最后的管弦乐作品，小提琴与大提琴如两位老友的对话。奥伊斯特拉赫与罗斯特罗波维奇两位巨匠珠联璧合，塞尔的乐队严整有力。"],
["Rigoletto","《弄臣》","Giuseppe Verdi","Tullio Serafin · Maria Callas",1955,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","激昂","夜晚"],"威尔第中期杰作，弄臣为女复仇反致爱女殒命的悲剧。公爵的《女人善变》人人会哼，末幕四重唱是歌剧写作的奇迹。塞拉芬与卡拉斯的演绎经典。"],
["Aida","《阿依达》","Giuseppe Verdi","Herbert von Karajan · Wiener Philharmoniker",1959,"Decca","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["壮丽","悲伤","激昂"],"埃及与埃塞俄比亚战争背景下的三角恋悲剧，《凯旋进行曲》气势恢弘。卡拉扬与苔巴尔迪的这版兼具宏大场面与细腻抒情，是‘大歌剧’的典范。"],
["Falstaff","《法尔斯塔夫》","Giuseppe Verdi","Arturo Toscanini · NBC Symphony",1950,"RCA","romantic",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","激昂","壮丽"],"威尔第八十岁的封笔喜剧杰作，取材莎翁笔下的胖骑士，以‘世界是个大玩笑’的赋格终场。托斯卡尼尼曾参与首演，这版权威而充满活力。"],
["Madama Butterfly","《蝴蝶夫人》","Giacomo Puccini","Herbert von Karajan · Maria Callas",1955,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","亲密","夜晚"],"痴情的日本少女苦等负心美国军官终至殉情，《晴朗的一天》催人泪下。卡拉斯把蝴蝶的天真与心碎演绎得入木三分，卡拉扬的乐队细腻动人。"],
["Turandot","《图兰朵》","Giacomo Puccini","Zubin Mehta · Sutherland · Pavarotti",1972,"Decca","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["壮丽","激昂","悲伤"],"普契尼未竟的绝笔，冰冷公主与神秘王子的传奇，《今夜无人入睡》响彻世界。梅塔指挥、萨瑟兰与帕瓦罗蒂主演的这版辉煌灿烂，气势磅礴。"],
["Die Meistersinger von Nürnberg","《纽伦堡的名歌手》","Richard Wagner","Eugen Jochum · Deutsche Oper Berlin",1976,"Deutsche Grammophon","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["壮丽","喜悦","庄严"],"瓦格纳唯一的喜剧乐剧，一曲对艺术、传统与创新的温暖礼赞，序曲辉煌灿烂。约胡姆的演绎宽厚从容，把这部长达四小时的杰作演得亲切动人。"],
["Parsifal","《帕西法尔》","Richard Wagner","Hans Knappertsbusch · Bayreuth Festival",1962,"Philips","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["庄严","沉思","疗愈"],"瓦格纳最后的‘舞台祝圣节庆剧’，关于救赎与慈悲的神圣冥想。克纳佩茨布施在拜罗伊特的这版以无比宽广的气息，被公认为《帕西法尔》的传奇诠释。"],
["Symphony No. 4","《第四交响曲》","Pyotr Ilyich Tchaikovsky","Yevgeny Mravinsky · Leningrad Philharmonic",1960,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["激昂","悲伤","壮丽"],"以‘命运’号角开篇的悲剧交响曲，末乐章却在民间狂欢中寻找慰藉。穆拉文斯基与列宁格勒爱乐锋利精准、张力逼人，是柴氏交响曲的黄金标准。"],
["Symphony No. 5","《第五交响曲》","Pyotr Ilyich Tchaikovsky","Yevgeny Mravinsky · Leningrad Philharmonic",1960,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["激昂","壮丽","夜晚"],"贯穿全曲的‘命运’主题从阴郁走向凯旋，圆号的慢乐章旋律优美动人。穆拉文斯基这版冷峻犀利、结构如钢，与第四、第六并称不朽的三部曲。"],
["The Nutcracker","《胡桃夹子》","Pyotr Ilyich Tchaikovsky","André Previn · London Symphony",1972,"EMI","romantic",["芭蕾","管弦乐"],["管弦乐团"],["喜悦","壮丽","疗愈"],"圣诞节永恒的童话芭蕾，《花之圆舞曲》《糖果仙子之舞》里钢片琴的叮咚晶莹梦幻。普列文与伦敦交响的全曲录音色彩缤纷、活色生香。"],
["Serenade for Strings","《弦乐小夜曲》","Pyotr Ilyich Tchaikovsky","Herbert von Karajan · Berliner Philharmoniker",1980,"Deutsche Grammophon","romantic",["管弦乐"],["管弦乐团"],["疗愈","亲密","喜悦"],"柴科夫斯基向莫扎特致敬的弦乐杰作，开篇庄严的圣咏与如歌的圆舞曲广受喜爱。卡拉扬的柏林爱乐弦乐浓稠温暖，是纯弦乐之美的极致。"],
["Symphony No. 8","《第八交响曲》","Antonín Dvořák","Rafael Kubelík · Berliner Philharmoniker",1966,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["喜悦","壮丽","疗愈"],"德沃夏克最阳光的交响曲，洋溢波希米亚田园的鸟鸣与舞曲。库贝利克作为捷克人，把这份乡土气息演绎得亲切自然、光彩照人。"],
["Slavonic Dances","《斯拉夫舞曲》","Antonín Dvořák","George Szell · Cleveland Orchestra",1965,"Sony","romantic",["管弦乐"],["管弦乐团"],["喜悦","激昂","壮丽"],"取材捷克与斯拉夫民间舞蹈的十六首管弦乐小品，活力四射、旋律动人。塞尔与克利夫兰乐团精准而热情的演绎，被公认为难以超越的范本。"],
["String Quartet No. 12 'American'","《第12弦乐四重奏“美国”》","Antonín Dvořák","Emerson String Quartet",1993,"Deutsche Grammophon","romantic",["室内乐"],["弦乐四重奏"],["喜悦","疗愈","亲密"],"德沃夏克在美国爱荷华乡间写下的四重奏，融入黑人灵歌与民谣气息，明快清新。爱默生四重奏的演绎温暖流畅，是室内乐入门的绝佳选择。"],
["Symphony No. 7","《第七交响曲》","Anton Bruckner","Herbert von Karajan · Wiener Philharmoniker",1989,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["庄严","壮丽","沉思"],"布鲁克纳最受欢迎的交响曲，慢乐章为悼念瓦格纳而作、崇高哀恸。卡拉扬生前最后的录音之一，把这座声音的大教堂建造得辉煌而虔诚。"],
["Symphony No. 8","《第八交响曲》","Anton Bruckner","Herbert von Karajan · Wiener Philharmoniker",1988,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["壮丽","庄严","沉思"],"布鲁克纳交响宇宙的顶点，长达八十分钟的宏伟建筑，末乐章诸主题最终辉煌汇合。卡拉扬的演绎气象恢弘、层层堆叠，令人肃然起敬。"],
["Symphony No. 4 'Romantic'","《第四交响曲“浪漫”》","Anton Bruckner","Karl Böhm · Wiener Philharmoniker",1973,"Decca","romantic",["交响曲"],["管弦乐团"],["壮丽","庄严","疗愈"],"布鲁克纳最易亲近的交响曲，开篇圆号在弦乐微光中吹出的号角如晨雾中的城堡。伯姆与维也纳爱乐的演绎温暖自然、气息宽广。"],
["Symphony No. 1 'Titan'","《第一交响曲“巨人”》","Gustav Mahler","Rafael Kubelík · Bavarian Radio Symphony",1967,"Deutsche Grammophon","romantic",["交响曲"],["管弦乐团"],["激昂","喜悦","壮丽"],"马勒交响生涯的起点，从自然的苏醒到葬礼进行曲（变奏自《雅克兄弟》），再到末乐章的凯旋。库贝利克的演绎清新灵动、充满生命力。"],
["Symphony No. 4","《第四交响曲》","Gustav Mahler","George Szell · Cleveland Orchestra",1965,"Sony","romantic",["交响曲","声乐/艺术歌曲"],["管弦乐团","人声"],["喜悦","疗愈","亲密"],"马勒最明朗轻盈的交响曲，以女高音描绘孩童眼中天堂生活的歌收尾。塞尔与克利夫兰乐团精雕细琢、透明典雅，是‘第四’最精致的诠释。"],
["Symphony No. 6 'Tragic'","《第六交响曲“悲剧”》","Gustav Mahler","John Barbirolli · New Philharmonia",1967,"EMI","romantic",["交响曲"],["管弦乐团"],["悲伤","激昂","壮丽"],"马勒最黑暗的交响曲，末乐章三记命运的‘铁锤’击碎英雄。巴比罗利的演绎充满炽热的悲情与人性温度，撕心裂肺、震撼人心。"],
["Symphony No. 8 'Symphony of a Thousand'","《第八交响曲“千人”》","Gustav Mahler","Georg Solti · Chicago Symphony",1971,"Decca","romantic",["交响曲","合唱/宗教"],["管弦乐团","合唱","人声"],["壮丽","庄严","喜悦"],"动用巨型乐队、双合唱团与童声的宏大颂歌，从拉丁圣灵赞美诗到歌德《浮士德》终场。索尔蒂与芝加哥交响的这版辉煌灿烂、排山倒海。"],
["Kindertotenlieder","《亡儿之歌》","Gustav Mahler","Kathleen Ferrier · Bruno Walter",1949,"Decca","romantic",["声乐/艺术歌曲"],["人声","管弦乐团"],["悲伤","沉思","亲密"],"以吕克特悼念亡子的诗谱成的深沉套曲，哀而不伤、终归慰藉。女低音费里尔温暖厚重的嗓音与瓦尔特的伴奏，成就了催人泪下的经典。"],
["Ein Heldenleben","《英雄的生涯》","Richard Strauss","Fritz Reiner · Chicago Symphony",1954,"RCA","romantic",["管弦乐"],["管弦乐团","小提琴"],["壮丽","激昂","庄严"],"施特劳斯以自己为主角的宏大交响诗，独奏小提琴描绘‘英雄的伴侣’娇媚多变。莱纳与芝加哥交响的演绎辉煌逼人，是展示乐队实力的名片。"],
["Der Rosenkavalier","《玫瑰骑士》","Richard Strauss","Herbert von Karajan · Elisabeth Schwarzkopf",1956,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["亲密","喜悦","悲伤"],"施特劳斯最受爱戴的歌剧，维也纳式的怀旧喜剧，终场三重唱美到令人落泪。卡拉扬与施瓦茨科普夫的这版典雅华美，被奉为不可超越的经典。"],
["Metamorphosen","《变形》","Richard Strauss","Herbert von Karajan · Berliner Philharmoniker",1980,"Deutsche Grammophon","romantic",["管弦乐"],["管弦乐团"],["悲伤","沉思","庄严"],"二战末为二十三件弦乐器而作的挽歌，哀悼被战火摧毁的德国文化，尾声引入《英雄交响曲》的葬礼动机。卡拉扬的弦乐浓稠深沉，痛彻心扉。"],
["Symphony No. 3 'Organ'","《第三交响曲“管风琴”》","Camille Saint-Saëns","Charles Munch · Boston Symphony",1959,"RCA","romantic",["交响曲"],["管弦乐团","管风琴","钢琴"],["壮丽","激昂","庄严"],"以管风琴的轰鸣加冕的辉煌交响曲，末乐章管风琴与乐队齐鸣的瞬间令人震撼。明希与波士顿交响的这版气势恢弘，是发烧友的试机名盘。"],
["Requiem","《安魂曲》","Gabriel Fauré","André Cluytens · Orchestre de la Société des Concerts",1962,"EMI","romantic",["合唱/宗教","声乐"],["合唱","管弦乐团"],["疗愈","悲伤","庄严"],"没有恐怖的末日审判、只有安宁的‘天堂’的温柔安魂曲，《在天堂里》如摇篮曲般抚慰。克路易坦的演绎纯净柔和，是抚平哀伤最美的音乐之一。"],
["Symphony in D minor","《d小调交响曲》","César Franck","Pierre Monteux · Chicago Symphony",1961,"RCA","romantic",["交响曲"],["管弦乐团"],["激昂","庄严","沉思"],"法国交响曲的瑰宝，以循环主题贯穿三个乐章，浑厚而充满管风琴般的音响。蒙都的演绎结构清晰、气息宽广，尽显弗兰克的虔诚与热情。"],
["Violin Concerto No. 1","《第一小提琴协奏曲》","Max Bruch","Jascha Heifetz · Malcolm Sargent",1962,"RCA","romantic",["协奏曲"],["小提琴","管弦乐团"],["悲伤","亲密","壮丽"],"最受喜爱的小提琴协奏曲之一，慢乐章如歌般深情绵长。海菲茨的演绎音色璀璨、气息宽广，把布鲁赫的浪漫抒情推向极致。"],
["Carmen","《卡门》","Georges Bizet","Georges Prêtre · Maria Callas",1964,"EMI","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["激昂","夜晚","悲伤"],"世界上最受欢迎的歌剧，自由奔放的吉普赛女郎与痴情士兵的爱情悲剧，《哈巴涅拉》《斗牛士之歌》无人不晓。卡拉斯把卡门的野性与宿命演绎得摄人心魄。"],
["Il barbiere di Siviglia","《塞维利亚的理发师》","Gioachino Rossini","Alceo Galliera · Maria Callas",1957,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["喜悦","激昂","亲密"],"意大利喜歌剧的巅峰，机灵的理发师费加罗撮合有情人，《快给大忙人让路》快嘴炫技令人捧腹。罗西尼的旋律活力四射，这版妙趣横生。"],
["Lucia di Lammermoor","《拉美莫尔的露琪亚》","Gaetano Donizetti","Tullio Serafin · Maria Callas",1953,"EMI","romantic",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","激昂","夜晚"],"美声歌剧的代表作，露琪亚被迫成婚后精神崩溃、杀夫的‘疯狂场景’是花腔女高音的终极试炼。卡拉斯以无与伦比的戏剧性演绎，惊心动魄。"],
["Norma","《诺尔玛》","Vincenzo Bellini","Tullio Serafin · Maria Callas",1954,"EMI","romantic",["歌剧","声乐"],["人声","合唱","管弦乐团"],["悲伤","庄严","亲密"],"美声歌剧的圣殿，女祭司诺尔玛的咏叹《圣洁的女神》是女高音的珠穆朗玛。卡拉斯把这个角色化为自己的代名词，庄严、脆弱而伟大。"],
["24 Caprices","《24首随想曲》","Niccolò Paganini","Itzhak Perlman",1972,"EMI","romantic",["独奏/键盘","室内乐"],["小提琴"],["激昂","专注","壮丽"],"小提琴技巧的圣经与魔鬼的试炼，第24首的主题被李斯特、勃拉姆斯、拉赫玛尼诺夫反复变奏。帕尔曼以炉火纯青的技术与歌唱性，从容驾驭这些绝技。"],
["Má vlast","《我的祖国》","Bedřich Smetana","Rafael Kubelík · Czech Philharmonic",1990,"Supraphon","romantic",["管弦乐"],["管弦乐团"],["壮丽","疗愈","庄严"],"捷克民族音乐的圣典，六首交响诗中的《伏尔塔瓦河》描绘大河奔流入海，家喻户晓。流亡多年的库贝利克归国指挥的这场现场，饱含赤子深情。"],
["Scheherazade","《舍赫拉查达》","Nikolai Rimsky-Korsakov","Thomas Beecham · Royal Philharmonic",1957,"EMI","romantic",["管弦乐"],["管弦乐团","小提琴"],["壮丽","夜晚","激昂"],"取材《一千零一夜》的交响组曲，独奏小提琴化身讲故事的王后，配器绚烂如东方织锦。比彻姆的演绎色彩缤纷、气象万千，是管弦乐色彩的盛宴。"],
["The Blue Danube & Waltzes","《蓝色多瑙河 · 圆舞曲集》","Johann Strauss II","Willi Boskovsky · Wiener Philharmoniker",1966,"Decca","romantic",["管弦乐"],["管弦乐团"],["喜悦","疗愈","壮丽"],"‘圆舞曲之王’的维也纳金色旋律，《蓝色多瑙河》几乎是奥地利的第二国歌。博斯科夫斯基领奏的维也纳爱乐醇厚地道，尽显新年音乐会的欢愉。"],
// 现代 扩充
["Sinfonietta","《小交响曲》","Leoš Janáček","Charles Mackerras · Vienna Philharmonic",1980,"Decca","modern",["管弦乐"],["管弦乐团","小号"],["壮丽","激昂","喜悦"],"以九支小号的辉煌铜管齐鸣开篇的独特杰作，充满捷克民间的生猛活力。雅纳切克七十岁焕发的创造力令人惊叹，麦克拉斯的演绎权威而灿烂。"],
["Symphony No. 4 'The Inextinguishable'","《第四交响曲“不灭”》","Carl Nielsen","Herbert Blomstedt · San Francisco Symphony",1988,"Decca","modern",["交响曲"],["管弦乐团","打击乐"],["激昂","壮丽","专注"],"以两组定音鼓的‘搏斗’象征生命意志不可摧毁的交响曲。丹麦作曲家尼尔森写于一战期间，布隆斯泰特的演绎充满原始的力量与光辉。"],
["Symphony No. 5","《第五交响曲》","Jean Sibelius","Herbert von Karajan · Berliner Philharmoniker",1965,"Deutsche Grammophon","modern",["交响曲"],["管弦乐团"],["壮丽","庄严","疗愈"],"终乐章那‘天鹅主题’的铜管摆动，据说来自西贝柳斯目睹十六只天鹅飞过的震撼。结尾六记断然的和弦坚定有力。卡拉扬的演绎宏伟壮丽。"],
["Violin Concerto","《d小调小提琴协奏曲》","Jean Sibelius","Jascha Heifetz · Walter Hendl",1959,"RCA","modern",["协奏曲"],["小提琴","管弦乐团"],["悲伤","激昂","夜晚"],"北欧最伟大的小提琴协奏曲，冷峻孤独又炽热奔放，末乐章被形容为‘北极熊的波兰舞曲’。海菲茨的演绎技术无懈可击、气质高冷，令人叹为观止。"],
["Rhapsody on a Theme of Paganini","《帕格尼尼主题狂想曲》","Sergei Rachmaninoff","Arthur Rubinstein · Fritz Reiner",1956,"RCA","modern",["协奏曲"],["钢琴","管弦乐团"],["激昂","亲密","喜悦"],"以帕格尼尼随想曲主题写成的二十四段变奏，第十八变奏那如泣如诉的甜美旋律因电影而家喻户晓。鲁宾斯坦的演绎优雅璀璨、深情动人。"],
["Symphony No. 2","《第二交响曲》","Sergei Rachmaninoff","André Previn · London Symphony",1973,"EMI","modern",["交响曲"],["管弦乐团"],["悲伤","疗愈","亲密"],"拉赫玛尼诺夫最浓情的交响曲，第三乐章单簧管吹出的绵长旋律美到令人心碎。普列文与伦敦交响的演绎宽广抒情，是这部作品的公认标杆。"],
["Vespers (All-Night Vigil)","《彻夜晚祷》","Sergei Rachmaninoff","Robert Shaw Festival Singers",1990,"Telarc","modern",["合唱/宗教","声乐"],["合唱"],["庄严","沉思","疗愈"],"东正教晚祷的无伴奏合唱杰作，男低音深不见底的低音如大地共鸣，《尼姑颂》宁静圣洁。拉赫玛尼诺夫希望以其中一段为自己送葬，庄严动人。"],
["String Quartet","《弦乐四重奏》","Claude Debussy","Quartetto Italiano",1965,"Philips","modern",["室内乐"],["弦乐四重奏"],["沉思","亲密","夜晚"],"德彪西唯一的弦乐四重奏，色彩流动、织体轻盈，与拉威尔的四重奏常成对出现。意大利四重奏的演绎音色细腻、气韵生动，法式印象的室内乐典范。"],
["Pelléas et Mélisande","《佩利亚斯与梅丽桑德》","Claude Debussy","Herbert von Karajan · Berliner Philharmoniker",1978,"EMI","modern",["歌剧","声乐"],["人声","管弦乐团"],["夜晚","沉思","悲伤"],"德彪西唯一完成的歌剧，以近乎低语的宣叙与朦胧的管弦，讲述一段幽暗宿命的三角恋。卡拉扬的演绎如梦似雾，把象征主义的暧昧之美烘托到极致。"],
["String Quartet","《弦乐四重奏》","Maurice Ravel","Quartetto Italiano",1965,"Philips","modern",["室内乐"],["弦乐四重奏"],["亲密","喜悦","沉思"],"拉威尔青年时代的杰作，第二乐章的拨弦轻盈俏皮。这部作品献给德彪西，二者的四重奏是法国印象派室内乐的双璧。意大利四重奏演绎精致澄澈。"],
["Gaspard de la nuit","《夜之幽灵》","Maurice Ravel","Martha Argerich",1974,"Deutsche Grammophon","modern",["独奏/键盘"],["钢琴"],["夜晚","激昂","专注"],"钢琴文献中最艰深的作品之一，描绘水妖、绞刑架与鬼精灵三幅暗夜画卷。阿格里奇的演绎技惊四座、色彩魔幻，把这部炫技诗篇弹得摄人心魄。"],
["Music for Strings, Percussion and Celesta","《为弦乐、打击乐与钢片琴而作的音乐》","Béla Bartók","Fritz Reiner · Chicago Symphony",1958,"RCA","modern",["管弦乐"],["管弦乐团","打击乐"],["夜晚","专注","激昂"],"巴托克最完美的杰作，缓慢的赋格与神秘的‘夜之音乐’曾用于库布里克电影《闪灵》。莱纳与芝加哥交响的演绎精准冷峻、张力惊人。"],
["Bluebeard's Castle","《蓝胡子公爵的城堡》","Béla Bartók","István Kertész · London Symphony",1965,"Decca","modern",["歌剧","声乐"],["人声","管弦乐团"],["夜晚","悲伤","庄严"],"仅两个角色的独幕歌剧，新娘逐一打开七道门、揭开蓝胡子的秘密，配器随之明暗变幻。凯尔特斯的演绎色彩浓烈、心理张力逼人。"],
["Piano Concertos Nos. 2 & 3","《第二 · 第三钢琴协奏曲》","Béla Bartók","Géza Anda · Ferenc Fricsay",1959,"Deutsche Grammophon","modern",["协奏曲"],["钢琴","管弦乐团"],["激昂","专注","夜晚"],"把钢琴当作打击乐器的凶悍杰作，节奏原始、夜之音乐神秘。同为匈牙利人的安达与弗里恰伊珠联璧合，是巴托克协奏曲的经典诠释。"],
["Symphony No. 5","《第五交响曲》","Sergei Prokofiev","Herbert von Karajan · Berliner Philharmoniker",1968,"Deutsche Grammophon","modern",["交响曲"],["管弦乐团"],["壮丽","激昂","庄严"],"普罗科菲耶夫献给‘自由人类精神’的战时交响曲，宏大庄严又不失锋芒。卡拉扬与柏林爱乐的演绎辉煌有力、光泽饱满，气势磅礴。"],
["Alexander Nevsky","《亚历山大·涅夫斯基》","Sergei Prokofiev","Fritz Reiner · Chicago Symphony",1959,"RCA","modern",["合唱/宗教","管弦乐"],["合唱","管弦乐团"],["壮丽","激昂","庄严"],"由爱森斯坦同名电影配乐改编的康塔塔，《冰湖大战》气势磅礴、《死亡战场》女中音的哀歌苍凉动人。莱纳与芝加哥交响的演绎震撼逼人。"],
["Symphony No. 7 'Leningrad'","《第七交响曲“列宁格勒”》","Dmitri Shostakovich","Leonard Bernstein · Chicago Symphony",1988,"Deutsche Grammophon","modern",["交响曲"],["管弦乐团"],["激昂","壮丽","悲伤"],"围城中的列宁格勒创作、以‘侵略主题’的军鼓渐强震撼世界的战时交响曲。伯恩斯坦与芝加哥交响的演绎宏大炽烈，把抵抗与哀悼演绎得撕心裂肺。"],
["Cello Concerto No. 1","《第一大提琴协奏曲》","Dmitri Shostakovich","Mstislav Rostropovich · Eugene Ormandy",1959,"Sony","modern",["协奏曲"],["大提琴","管弦乐团"],["激昂","悲伤","专注"],"为罗斯特罗波维奇量身打造、以他四天背下首演的名作，开篇四音动机贯穿全曲、尖锐而执拗。这版由被题献者亲自首演录制，权威无匹。"],
["24 Preludes and Fugues","《24首前奏曲与赋格》","Dmitri Shostakovich","Tatiana Nikolayeva",1987,"Hyperion","modern",["独奏/键盘"],["钢琴"],["沉思","专注","悲伤"],"向巴赫《平均律》致敬、遍历二十四调的钢琴巨著，兼具对位的严谨与二十世纪的忧思。首演者尼古拉耶娃倾注一生的演绎深沉而权威。"],
["Violin Concerto No. 1","《第一小提琴协奏曲》","Dmitri Shostakovich","David Oistrakh · Yevgeny Mravinsky",1956,"Melodiya","modern",["协奏曲"],["小提琴","管弦乐团"],["悲伤","激昂","夜晚"],"在斯大林高压下秘藏多年才首演的杰作，夜曲的沉思、诙谐曲的癫狂与帕萨卡利亚的悲怆交织。题献者奥伊斯特拉赫的演绎深刻而炽烈。"],
["Pierrot Lunaire","《月光下的皮埃罗》","Arnold Schoenberg","Pierre Boulez · Ensemble",1977,"Sony","modern",["室内乐","声乐/艺术歌曲"],["人声","钢琴","长笛"],["夜晚","沉思","激昂"],"以‘念唱’介于说与唱之间的先锋杰作，二十一首诗描绘月光下小丑的癫狂幻象。布列兹的演绎精准冷冽，是理解表现主义与勋伯格的钥匙。"],
["Wozzeck","《沃采克》","Alban Berg","Pierre Boulez · Paris Opera",1966,"Sony","modern",["歌剧","声乐"],["人声","管弦乐团"],["悲伤","夜晚","激昂"],"二十世纪最伟大的歌剧之一，卑微士兵沃采克被侮辱、被逼疯、终至杀妻投水的悲剧。贝尔格以严密结构包裹汹涌情感，布列兹的演绎锋利震撼。"],
["Fantasia on a Theme by Thomas Tallis","《塔利斯主题幻想曲》","Ralph Vaughan Williams","John Barbirolli · Sinfonia of London",1963,"EMI","modern",["管弦乐"],["管弦乐团","弦乐四重奏"],["疗愈","沉思","庄严"],"以十六世纪塔利斯的赞美诗为主题、为双弦乐团而作的英伦瑰宝，音响空灵如大教堂回声。巴比罗利的演绎宽广深情，被誉为最动人的英国弦乐音乐。"],
["The Planets","《行星组曲》","Gustav Holst","Herbert von Karajan · Wiener Philharmoniker",1961,"Decca","modern",["管弦乐"],["管弦乐团","管风琴"],["壮丽","激昂","夜晚"],"以七大行星占星性格谱成的宏大组曲，《火星》的战争律动与《木星》的欢乐颂歌广为流传，深刻影响了后世电影配乐。卡拉扬的演绎辉煌壮丽。"],
["Enigma Variations","《谜语变奏曲》","Edward Elgar","John Barbirolli · Philharmonia",1962,"EMI","modern",["管弦乐"],["管弦乐团"],["疗愈","亲密","壮丽"],"埃尔加为友人们画的十四幅音乐肖像，第九段《宁录》庄严深情、成为英国追思仪式的必备。巴比罗利的演绎温暖高贵，尽显英伦风范。"],
["Adagio for Strings","《弦乐柔板》","Samuel Barber","Leonard Bernstein · Los Angeles Philharmonic",1982,"Deutsche Grammophon","modern",["管弦乐"],["管弦乐团"],["悲伤","疗愈","沉思"],"美国最著名的哀悼音乐，缓缓攀升至撕裂般的高潮再归于寂静，常现于国葬与电影。伯恩斯坦的演绎极尽绵长与深情，催人泪下。"],
["West Side Story","《西区故事》","Leonard Bernstein",  "Leonard Bernstein · Studio Cast",1984,"Deutsche Grammophon","modern",["歌剧","管弦乐"],["管弦乐团","人声"],["激昂","悲伤","喜悦"],"把《罗密欧与朱丽叶》搬到纽约街头帮派的音乐剧杰作，《Tonight》《Maria》《America》融合爵士、拉丁与古典。伯恩斯坦亲自指挥的这版权威而炽热。"],
["Fanfare & Appalachian Spring","《平凡人的号角 · 阿巴拉契亚之春》","Aaron Copland","Leonard Bernstein · New York Philharmonic",1966,"Sony","modern",["管弦乐"],["管弦乐团","小号"],["壮丽","激昂","疗愈"],"《平凡人的号角》以铜管与定音鼓向普通劳动者致敬，庄严而崇高。伯恩斯坦作为科普兰音乐最有力的推广者，演绎充满美式的自豪与开阔。"],
["An American in Paris","《一个美国人在巴黎》","George Gershwin","Leonard Bernstein · New York Philharmonic",1959,"Sony","modern",["管弦乐"],["管弦乐团"],["喜悦","激昂","夜晚"],"格什温游历巴黎的音乐明信片，出租车喇叭与爵士蓝调交织出都市的喧闹与乡愁。伯恩斯坦的演绎活力四射、地道摩登。"],
["The Young Person's Guide to the Orchestra","《青少年管弦乐指南》","Benjamin Britten","Benjamin Britten · London Symphony",1963,"Decca","modern",["管弦乐"],["管弦乐团"],["喜悦","专注","壮丽"],"以珀塞尔主题让乐队各声部轮番亮相、最后汇成辉煌赋格的名作，是认识管弦乐团的最佳入门。作曲家亲自指挥，权威而生动。"],
["Serenade for Tenor, Horn and Strings","《为男高音、圆号与弦乐的小夜曲》","Benjamin Britten","Peter Pears · Dennis Brain · Britten",1963,"Decca","modern",["声乐/艺术歌曲","室内乐"],["人声","弦乐四重奏"],["夜晚","沉思","亲密"],"以英诗谱成、由圆号的自然泛音框起的黄昏之歌。为布里顿的伴侣皮尔斯与传奇圆号家丹尼斯·布莱恩量身而作，三位一体的演绎无可替代。"],
// 当代 扩充
["Different Trains","《不同的列车》","Steve Reich","Kronos Quartet",1989,"Nonesuch","contemporary",["室内乐"],["弦乐四重奏"],["悲伤","专注","夜晚"],"赖希把童年横穿美国的火车记忆、与同时代欧洲犹太人被运往集中营的列车并置，用录音人声的音高谱写弦乐旋律。克罗诺斯四重奏的演绎震撼人心。"],
["Electric Counterpoint","《电子对位》","Steve Reich","Pat Metheny",1987,"Nonesuch","contemporary",["室内乐"],["吉他"],["专注","疗愈","喜悦"],"为多轨吉他叠录而作的简约名篇，层层交织的音型如闪烁的织锦。爵士吉他大师帕特·梅西尼一人分饰多声部，脉动明亮、令人沉醉。"],
["Einstein on the Beach","《海滩上的爱因斯坦》","Philip Glass","Philip Glass Ensemble",1979,"CBS","contemporary",["歌剧"],["管弦乐团","人声"],["专注","夜晚","激昂"],"格拉斯与罗伯特·威尔逊颠覆歌剧传统的四幕巨作——没有情节、长达五小时、以数字与唱名代替歌词。简约主义的里程碑，重新定义了何为歌剧。"],
["Violin Concerto No. 1","《第一小提琴协奏曲》","Philip Glass","Gidon Kremer · Christoph von Dohnányi",1993,"Deutsche Grammophon","contemporary",["协奏曲"],["小提琴","管弦乐团"],["夜晚","沉思","疗愈"],"格拉斯为纪念爱好小提琴的父亲而作，是简约主义最抒情、最易亲近的协奏曲之一。克莱默的演绎在不断循环的琶音中流淌出温暖的忧伤。"],
["Nixon in China","《尼克松在中国》","John Adams","Edo de Waart · Orchestra of St. Luke's",1987,"Nonesuch","contemporary",["歌剧"],["管弦乐团","人声"],["壮丽","激昂","沉思"],"以1972年尼克松访华为题材的当代歌剧杰作，把新闻事件升华为关于历史与人性的沉思。亚当斯的简约脉动与浪漫抒情交织，首演阵容的这版权威动人。"],
["Harmonielehre","《和声学》","John Adams","Simon Rattle · City of Birmingham Symphony",1994,"EMI","contemporary",["管弦乐"],["管弦乐团"],["壮丽","激昂","专注"],"亚当斯向晚期浪漫致敬的宏大管弦乐，把简约的脉动注入马勒式的激情与音响。开篇如打桩机般的强奏充满能量，拉特尔的演绎辉煌壮丽。"],
["Fratres","《兄弟》","Arvo Pärt","Gidon Kremer · Keith Jarrett",1983,"ECM New Series","contemporary",["室内乐"],["小提琴","钢琴"],["沉思","疗愈","庄严"],"佩尔特被演绎版本最多的作品，同一段圣咏式的和声在不同乐器编制中反复回旋，静谧而崇高。克莱默的小提琴版凄美纯净，直抵心灵。"],
["Spiegel im Spiegel","《镜中镜》","Arvo Pärt","Vladimir Spivakov · Sergej Bezrodny",1999,"ECM New Series","contemporary",["室内乐"],["小提琴","钢琴"],["疗愈","亲密","沉思"],"极简至极的杰作——钢琴的分解和弦与小提琴绵长的音符交替上行，宁静得近乎透明。它抚慰了无数现代心灵，是‘神圣极简主义’的代名词。"],
["The Protecting Veil","《保护的面纱》","John Tavener","Steven Isserlis · Gennadi Rozhdestvensky",1992,"Virgin","contemporary",["协奏曲"],["大提琴","管弦乐团"],["疗愈","沉思","庄严"],"塔文纳为大提琴与弦乐团而作、以东正教对圣母的敬拜为灵感的冥想杰作，独奏大提琴如人声般在高音区吟唱。伊瑟利斯的演绎空灵圣洁，令人沉醉。"],
["Concerto Grosso No. 1","《第一大协奏曲》","Alfred Schnittke","Gidon Kremer · Heinrich Schiff",1988,"Deutsche Grammophon","contemporary",["协奏曲","室内乐"],["小提琴","管弦乐团","羽管键琴"],["激昂","夜晚","沉思"],"施尼特凯‘复风格’的代表作，巴洛克的典雅、探戈的媚俗与现代的尖锐荒诞并置、相互撕扯。克莱默的演绎凌厉而戏谑，是当代最迷人的杰作之一。"],
["Offertorium","《奉献经》","Sofia Gubaidulina","Gidon Kremer · Charles Dutoit",1989,"Deutsche Grammophon","contemporary",["协奏曲"],["小提琴","管弦乐团"],["沉思","悲伤","庄严"],"古拜杜丽娜为克莱默而作、以巴赫《音乐的奉献》主题为核心的小提琴协奏曲，充满深沉的宗教献祭意味。神秘、痛切而崇高，克莱默的演绎虔诚投入。"],
["Crouching Tiger, Hidden Dragon","《卧虎藏龙》","Tan Dun","Yo-Yo Ma · Shanghai Symphony",2000,"Sony","contemporary",["管弦乐"],["大提琴","管弦乐团"],["悲伤","夜晚","疗愈"],"谭盾为李安电影所作、赢得奥斯卡的配乐，马友友的大提琴如江湖侠客的叹息，融合中国民乐与西方管弦。东方意境与好莱坞叙事的完美交融。"],
["The Blue Notebooks","《蓝色笔记本》","Max Richter","Max Richter",2004,"Fat Cat / DG","contemporary",["管弦乐","室内乐"],["钢琴","管弦乐团"],["悲伤","疗愈","夜晚"],"后极简主义的当代经典，钢琴、弦乐与朗读交织成一部关于战争与记忆的沉思。《On the Nature of Daylight》被无数电影引用，忧伤得美到令人心碎。"],
["In C","《C调》","Terry Riley","Terry Riley & Ensemble",1968,"Columbia","contemporary",["室内乐"],["管弦乐团","打击乐"],["专注","喜悦","疗愈"],"简约主义的开山之作——五十三个短小音型，由任意数量的乐手自由重复推进，在C调的脉动中缓缓演化。这场1968年的首演录音开启了一个全新的音乐时代。"]
];

// ---- 第二批作曲家小传 ----
const BIOS2 = {
"Arcangelo Corelli":{zh:"阿尔坎杰罗·科雷利",born:1653,died:1713,country:"意大利",role:"作曲家 · 小提琴家",bio:"巴洛克小提琴与合奏音乐的奠基者。他确立了大协奏曲与三重奏鸣曲的范式，旋律纯净均衡，《圣诞协奏曲》流传至今，影响了从维瓦尔第到亨德尔的一整代作曲家。"},
"Georg Philipp Telemann":{zh:"格奥尔格·菲利普·泰勒曼",born:1681,died:1767,country:"德国",role:"作曲家",bio:"巴洛克最高产的作曲家，生前声名甚至超过好友巴赫。他融合德、法、意与波兰民间风格，作品数量惊人，《餐桌音乐》是其器乐代表作。"},
"Jean-Philippe Rameau":{zh:"让-菲利普·拉莫",born:1683,died:1764,country:"法国",role:"作曲家 · 音乐理论家",bio:"法国巴洛克的集大成者，也是奠定现代和声理论的先驱。他的歌剧与羽管键琴作品和声大胆、色彩细腻，把法国宫廷音乐推向了新的高度。"},
"Christoph Willibald Gluck":{zh:"克里斯托夫·威利巴尔德·格鲁克",born:1714,died:1787,country:"德国 / 奥地利",role:"作曲家",bio:"歌剧改革的旗手。他反对炫技至上的旧习，主张音乐服务于戏剧的真挚情感，《奥菲欧与尤丽狄茜》质朴动人，为莫扎特与后世歌剧铺平了道路。"},
"Johann Pachelbel":{zh:"约翰·帕赫贝尔",born:1653,died:1706,country:"德国",role:"作曲家 · 管风琴师",bio:"巴洛克中期的德国管风琴大师，与巴赫家族交往密切。今日他几乎因一首《D大调卡农》而不朽——那首无处不在的婚礼名曲。"},
"Tomaso Albinoni":{zh:"托马索·阿尔比诺尼",born:1671,died:1751,country:"意大利",role:"作曲家",bio:"威尼斯巴洛克作曲家，以协奏曲与歌剧闻名于世。后人据其残稿写成的《g小调柔板》如泣如诉，让他的名字家喻户晓。"},
"Niccolò Paganini":{zh:"尼科罗·帕格尼尼",born:1782,died:1840,country:"意大利",role:"作曲家 · 小提琴家",bio:"史上最传奇的小提琴炫技家，技艺高超到被传‘将灵魂卖给魔鬼’。他的《24首随想曲》拓展了小提琴技巧的疆界，其主题被李斯特、勃拉姆斯、拉赫玛尼诺夫反复变奏。"},
"Gioachino Rossini":{zh:"焦阿基诺·罗西尼",born:1792,died:1868,country:"意大利",role:"作曲家",bio:"意大利喜歌剧之王，以《塞维利亚的理发师》《威廉·退尔》等作横扫欧洲，旋律活力四射、‘渐强’手法令人上瘾。三十七岁便功成身退，转而钻研美食。"},
"Gaetano Donizetti":{zh:"加埃塔诺·多尼采蒂",born:1797,died:1848,country:"意大利",role:"作曲家",bio:"美声歌剧的多产大师，一生写下近七十部歌剧。《拉美莫尔的露琪亚》的‘疯狂场景’与喜剧《爱之甘醇》尽显他旋律与戏剧的双重天赋。"},
"Vincenzo Bellini":{zh:"温琴佐·贝利尼",born:1801,died:1835,country:"意大利",role:"作曲家",bio:"美声歌剧最纯粹的抒情诗人，以绵长如呼吸的旋律著称，《诺尔玛》中的《圣洁的女神》是女高音的试金石。三十三岁英年早逝，肖邦的夜曲深受其影响。"},
"Georges Bizet":{zh:"乔治·比才",born:1838,died:1875,country:"法国",role:"作曲家",bio:"法国歌剧的天才，《卡门》以炽热的旋律与真实主义的戏剧成为世界上演出最多的歌剧。可惜他在首演失利后不久猝逝，未及见证这部杰作征服全球。"},
"Camille Saint-Saëns":{zh:"卡米尔·圣-桑",born:1835,died:1921,country:"法国",role:"作曲家 · 管风琴家",bio:"法国音乐的多面手与神童，作品优雅工整、配器华丽。《管风琴交响曲》《动物狂欢节》《骷髅之舞》广受喜爱，一生横跨浪漫主义到现代的漫长岁月。"},
"Gabriel Fauré":{zh:"加布里埃尔·福雷",born:1845,died:1924,country:"法国",role:"作曲家 · 管风琴家",bio:"连接浪漫主义与现代的法国大师，和声细腻、气质内敛。《安魂曲》温柔安详，《帕凡舞曲》《西西里舞曲》优美动人，他还是拉威尔等人的良师。"},
"César Franck":{zh:"塞萨尔·弗兰克",born:1822,died:1890,country:"比利时 / 法国",role:"作曲家 · 管风琴家",bio:"晚期浪漫的法国-比利时大师，以循环主题手法构筑严整而虔诚的音乐。《d小调交响曲》《小提琴奏鸣曲》是其代表作，管风琴般的厚重音响独树一帜。"},
"Max Bruch":{zh:"马克斯·布鲁赫",born:1838,died:1920,country:"德国",role:"作曲家",bio:"德国晚期浪漫作曲家，以旋律的深情绵长著称。《第一小提琴协奏曲》与《苏格兰幻想曲》是小提琴曲目的常青树，尽管他自己更看重那些已被遗忘的合唱作品。"},
"Bedřich Smetana":{zh:"贝德里赫·斯美塔那",born:1824,died:1884,country:"捷克",role:"作曲家",bio:"捷克民族音乐之父。交响诗套曲《我的祖国》（含《伏尔塔瓦河》）与歌剧《被出卖的新娘》奠定了捷克的民族之声。晚年失聪，在耳鸣中写下深情的作品。"},
"Alexander Borodin":{zh:"亚历山大·鲍罗丁",born:1833,died:1887,country:"俄国",role:"作曲家 · 化学家",bio:"俄罗斯‘强力集团’成员，本职却是杰出的化学家，作曲只是‘周末的消遣’。《伊戈尔王》中的《波罗维茨舞曲》与第二弦乐四重奏的《夜曲》旋律迷人。"},
"Nikolai Rimsky-Korsakov":{zh:"尼古拉·里姆斯基-科萨科夫",born:1844,died:1908,country:"俄国",role:"作曲家",bio:"俄罗斯配器法的一代宗师，色彩绚烂如东方织锦。《舍赫拉查达》《西班牙随想曲》是管弦乐色彩的教科书，他还教出了斯特拉文斯基等一代大家。"},
"Johann Strauss II":{zh:"小约翰·施特劳斯",born:1825,died:1899,country:"奥地利",role:"作曲家",bio:"‘圆舞曲之王’，维也纳金色年华的化身。《蓝色多瑙河》《皇帝圆舞曲》与轻歌剧《蝙蝠》让维也纳的舞步风靡世界，至今仍是新年音乐会的主角。"},
"Anton Bruckner":{zh:"安东·布鲁克纳",born:1824,died:1896,country:"奥地利",role:"作曲家 · 管风琴师",bio:"晚期浪漫主义交响曲的巨匠，虔诚的天主教徒。他的九部交响曲宏伟庄严、如声音的大教堂，把瓦格纳的和声与管风琴般的音响熔铸成漫长而崇高的冥想。生前饱受质疑，身后方被尊为大师。"},
"Leoš Janáček":{zh:"莱奥什·雅纳切克",born:1854,died:1928,country:"捷克",role:"作曲家",bio:"捷克现代音乐的独行者，晚年焕发惊人创造力。他从摩拉维亚方言的语调中提炼旋律，歌剧《耶奴发》、《小交响曲》与《格拉高利弥撒》充满生猛的原始活力。"},
"Carl Nielsen":{zh:"卡尔·尼尔森",born:1865,died:1931,country:"丹麦",role:"作曲家",bio:"丹麦最伟大的作曲家，与西贝柳斯并称北欧双璧。他的六部交响曲以‘渐进调性’与充沛的生命意志著称，《第四“不灭”》以定音鼓的搏斗歌颂生命不可摧毁。"},
"Ralph Vaughan Williams":{zh:"拉尔夫·沃恩·威廉斯",born:1872,died:1958,country:"英国",role:"作曲家",bio:"二十世纪英国音乐复兴的核心。他采集英格兰民歌、钻研都铎时代复调，写下《塔利斯主题幻想曲》《云雀高飞》等空灵之作，塑造出独特的英伦田园之声。"},
"Gustav Holst":{zh:"古斯塔夫·霍尔斯特",born:1874,died:1934,country:"英国",role:"作曲家",bio:"沃恩·威廉斯的挚友，英国作曲家。管弦乐组曲《行星》以占星意象与瑰丽配器广为流传，《木星》的颂歌旋律深入人心，深刻影响了后世的电影配乐。"},
"William Walton":{zh:"威廉·沃尔顿",born:1902,died:1983,country:"英国",role:"作曲家",bio:"二十世纪英国作曲家，风格华丽而带爵士色彩。清唱剧《伯沙撒的盛宴》气势磅礴，《加冕进行曲》庄严辉煌，他还为奥利弗的莎剧电影写下杰出配乐。"},
"Francis Poulenc":{zh:"弗朗西斯·普朗克",born:1899,died:1963,country:"法国",role:"作曲家",bio:"法国‘六人团’成员，兼具巴黎沙龙的俏皮与宗教的虔诚，被形容为‘一半僧侣、一半顽童’。《荣耀经》《管风琴协奏曲》与歌剧《加尔默罗会修女的对话》真挚动人。"},
"Anton Webern":{zh:"安东·韦伯恩",born:1883,died:1945,country:"奥地利",role:"作曲家",bio:"第二维也纳乐派的一员，勋伯格的学生。他把十二音技法推向极致的精简与凝练，作品短小、音响稀疏如点彩，深刻影响了战后的序列主义先锋。"},
"Paul Hindemith":{zh:"保罗·欣德米特",born:1895,died:1963,country:"德国 / 美国",role:"作曲家 · 中提琴家",bio:"二十世纪德国的作曲大家与理论家，倡导‘实用音乐’。歌剧《画家马蒂斯》及其交响曲是其代表作，纳粹上台后流亡美国，作品以严整的对位与新调性著称。"},
"Arthur Honegger":{zh:"阿尔蒂尔·奥涅格",born:1892,died:1955,country:"瑞士 / 法国",role:"作曲家",bio:"法国‘六人团’成员，风格厚重而富戏剧性。管弦乐《太平洋231号》以音乐描绘蒸汽机车的轰鸣，《第三“礼拜仪式”交响曲》则是战后祈求和平的呐喊。"},
"Samuel Barber":{zh:"塞缪尔·巴伯",born:1910,died:1981,country:"美国",role:"作曲家",bio:"二十世纪美国最抒情的作曲家，坚守浪漫主义的旋律之美。《弦乐柔板》成为全世界最著名的哀悼音乐，他的小提琴协奏曲与艺术歌曲同样动人。"},
"Leonard Bernstein":{zh:"伦纳德·伯恩斯坦",born:1918,died:1990,country:"美国",role:"作曲家 · 指挥家 · 钢琴家",bio:"二十世纪美国音乐的旗帜，横跨古典与百老汇的全才。他既是马勒最炽热的诠释者与传奇指挥，又写下《西区故事》《坎迪德》，还以电视讲座向大众普及古典音乐。"},
"Charles Ives":{zh:"查尔斯·艾夫斯",born:1874,died:1954,country:"美国",role:"作曲家",bio:"美国音乐的孤独先知，白天经营保险、业余作曲，却大胆预示了多调性、拼贴与微分音。他把赞美诗、进行曲与不协和音并置，《未被回答的问题》深邃神秘，生前几乎无人赏识。"},
"Witold Lutosławski":{zh:"维托尔德·卢托斯瓦夫斯基",born:1913,died:1994,country:"波兰",role:"作曲家 · 指挥家",bio:"二十世纪波兰最重要的作曲家之一。他发展出‘可控偶然’技法，让乐手在框架内自由演奏，《乐队协奏曲》与第三交响曲兼具严谨结构与丰富色彩。"},
"Toru Takemitsu":{zh:"武满彻",born:1930,died:1996,country:"日本",role:"作曲家",bio:"二十世纪日本最重要的作曲家，融合西方现代技法与东方的静默美学。《十一月的阶梯》让尺八、琵琶与西方乐团对话，其音乐如枯山水般空灵，深受西方推崇。"},
"Alfred Schnittke":{zh:"阿尔弗雷德·施尼特凯",born:1934,died:1998,country:"苏联 / 俄国",role:"作曲家",bio:"苏联后期最具影响力的作曲家，‘复风格’的代表。他把巴洛克、古典、探戈与现代的尖锐荒诞拼贴并置，音乐充满讽刺、痛苦与形而上的追问。"},
"Sofia Gubaidulina":{zh:"索菲亚·古拜杜丽娜",born:1931,died:2025,country:"苏联 / 俄国",role:"作曲家",bio:"俄罗斯当代最深刻的作曲家之一，作品充满强烈的宗教精神与象征意味。《奉献经》等杰作在克莱默等大师的推广下享誉世界，音乐神秘、痛切而崇高。"},
"John Tavener":{zh:"约翰·塔文纳",born:1944,died:2013,country:"英国",role:"作曲家",bio:"英国当代作曲家，皈依东正教后写下大量神圣极简风格的作品。《保护的面纱》《为阿西娜之歌》宁静空灵，后者曾在戴安娜王妃葬礼上奏响，抚慰人心。"},
"Tan Dun":{zh:"谭盾",born:1957,country:"中国",role:"作曲家 · 指挥家",bio:"享誉国际的中国当代作曲家，善于融合中国传统、自然之声（水、纸、石）与西方管弦。电影《卧虎藏龙》配乐为他赢得奥斯卡，作品充满东方哲思与实验精神。"},
"Terry Riley":{zh:"特里·莱利",born:1935,country:"美国",role:"作曲家",bio:"简约主义的开创者之一。1964年的《In C》以自由重复的短小音型开启了整个简约音乐运动，深刻影响了赖希、格拉斯乃至摇滚与电子乐界。"},
"Max Richter":{zh:"马克斯·里希特",born:1966,country:"德国 / 英国",role:"作曲家",bio:"当代最受欢迎的后极简主义作曲家之一。他把古典、电子与氛围音乐相融，《蓝色笔记本》《Sleep》与重构版维瓦尔第《四季》风靡全球，也常见于影视配乐。"}
};

// ---- 作曲家小传（键 = 上面的 c 字段）----
const BIOS = {
"Hildegard von Bingen":{zh:"希尔德加德·冯·宾根",born:1098,died:1179,country:"神圣罗马帝国",role:"作曲家 · 修道院长 · 神秘主义者",bio:"中世纪最非凡的女性之一——修道院长、神学家、医者、幻视者,也是最早留下姓名的作曲家。她的单声圣咏音域宽广、旋律奔放,充满神秘的通神体验,九百年后依然动人。"},
"Pérotin":{zh:"佩罗坦",life:"活跃约 1200",country:"法国",role:"作曲家",bio:"巴黎圣母院乐派的核心人物,把两声部的奥尔加农扩展为三声、四声的宏伟复调。他是最早探索多声部纵向和声的作曲家之一,西方复调建筑的奠基者。"},
"Guillaume de Machaut":{zh:"纪尧姆·德·马肖",born:1300,died:1377,country:"法国",role:"作曲家 · 诗人",bio:"中世纪‘新艺术’(Ars Nova)的领袖,既是伟大的诗人也是作曲家。他的《圣母弥撒》是史上第一部由单一作曲家完成的完整弥撒套曲,节奏之复杂领先时代。"},
"Josquin des Prez":{zh:"若斯坎·德普雷",born:1450,died:1521,country:"佛兰德斯",role:"作曲家",bio:"文艺复兴盛期最伟大的复调大师,被同代人尊为‘音符的主人’。他把模仿对位发展到炉火纯青,情感表达细腻,深刻影响了整个欧洲的音乐语言。"},
"Giovanni Pierluigi da Palestrina":{zh:"帕勒斯特里那",born:1525,died:1594,country:"意大利",role:"作曲家",bio:"罗马乐派的代表,以平滑无瑕的对位写作被后世奉为宗教复调的典范。传说他的《马尔切鲁斯教皇弥撒》让特伦特会议相信复调音乐可以保留在教会仪式中。"},
"Thomas Tallis":{zh:"托马斯·塔利斯",born:1505,died:1585,country:"英格兰",role:"作曲家 · 管风琴师",bio:"英国文艺复兴音乐的泰斗,历经四朝宗教剧变而屹立不倒。四十声部的经文歌《Spem in Alium》是纯人声复调的奇迹,至今无人超越。"},
"William Byrd":{zh:"威廉·伯德",born:1540,died:1623,country:"英格兰",role:"作曲家",bio:"塔利斯的学生,英国最伟大的文艺复兴作曲家。身为新教英格兰中坚守信仰的天主教徒,他把隐秘的虔诚写进精雕细琢的弥撒与经文歌,同时也是键盘音乐的先驱。"},
"Claudio Monteverdi":{zh:"克劳迪奥·蒙特威尔第",born:1567,died:1643,country:"意大利",role:"作曲家",bio:"横跨文艺复兴与巴洛克的枢纽人物。他的《奥菲欧》是西方第一部真正的歌剧,《圣母晚祷》熔古今于一炉。他把音乐的重心从复调转向以情感为核心的旋律,开启了新时代。"},
"Johann Sebastian Bach":{zh:"约翰·塞巴斯蒂安·巴赫",born:1685,died:1750,country:"德国",role:"作曲家 · 管风琴师",bio:"西方音乐史的中心。巴赫把巴洛克的对位技艺推向前无古人的完满,《平均律》《赋格的艺术》《马太受难曲》《b小调弥撒》构成一座座不可逾越的高峰。他生前以管风琴演奏闻名,身后被尊为‘音乐之父’。"},
"George Frideric Handel":{zh:"乔治·弗里德里希·亨德尔",born:1685,died:1759,country:"德国 / 英国",role:"作曲家",bio:"与巴赫同年生于德国,却在伦敦成就辉煌的国际巨星。他先征服意大利歌剧,再以英语清唱剧《弥赛亚》风靡英伦。旋律恢弘大气,是巴洛克最成功的公众音乐家。"},
"Antonio Vivaldi":{zh:"安东尼奥·维瓦尔第",born:1678,died:1741,country:"意大利",role:"作曲家 · 小提琴家 · 神父",bio:"威尼斯的‘红发神父’,在女子孤儿院任教并写下大量协奏曲。他定型了快—慢—快三乐章的独奏协奏曲,《四季》以音乐描绘自然,是史上最流行的古典作品之一。"},
"Henry Purcell":{zh:"亨利·珀塞尔",born:1659,died:1695,country:"英格兰",role:"作曲家",bio:"英国巴洛克最伟大的作曲家,三十六岁英年早逝。他的歌剧《狄多与埃涅阿斯》以‘狄多的悲叹’达到心碎的顶点,融合了英语的抑扬与意大利、法国的风格。"},
"Domenico Scarlatti":{zh:"多梅尼科·斯卡拉蒂",born:1685,died:1757,country:"意大利 / 西班牙",role:"作曲家 · 羽管键琴家",bio:"与巴赫、亨德尔同年出生,长期在西班牙宫廷任职。他写下五百五十余首单乐章键盘奏鸣曲,充满西班牙民间的色彩、交叉手与大胆的和声,是键盘音乐的宝库。"},
"Joseph Haydn":{zh:"约瑟夫·海顿",born:1732,died:1809,country:"奥地利",role:"作曲家",bio:"‘交响曲之父’与‘弦乐四重奏之父’。在埃斯特哈齐宫廷供职数十年,他几乎凭一己之力确立了古典时期的核心体裁与曲式,机智幽默、工艺精湛,是莫扎特的挚友、贝多芬的老师。"},
"Wolfgang Amadeus Mozart":{zh:"沃尔夫冈·阿玛迪乌斯·莫扎特",born:1756,died:1791,country:"奥地利",role:"作曲家",bio:"音乐史上罕见的全才天才,三十五年短暂一生几乎在每个体裁都留下不朽杰作。他的旋律臻于天然的完美,歌剧洞悉人性,协奏曲优雅深情。莫扎特让复杂显得毫不费力。"},
"Ludwig van Beethoven":{zh:"路德维希·凡·贝多芬",born:1770,died:1827,country:"德国",role:"作曲家",bio:"从古典迈向浪漫的巨人。他在逐渐失聪的绝境中,用意志把交响曲、奏鸣曲、四重奏撑向前所未有的规模与深度。《第九交响曲》的《欢乐颂》是人类团结的永恒宣言。"},
"Franz Schubert":{zh:"弗朗茨·舒伯特",born:1797,died:1828,country:"奥地利",role:"作曲家",bio:"艺术歌曲之王,三十一年短暂生命里写下逾六百首歌曲与大量器乐杰作。他把诗与旋律的结合推向极致,《冬之旅》《魔王》《鳟鱼》五重奏至今传唱,晚期作品深邃动人。"},
"Frédéric Chopin":{zh:"弗雷德里克·肖邦",born:1810,died:1849,country:"波兰 / 法国",role:"作曲家 · 钢琴家",bio:"‘钢琴诗人’,几乎只为钢琴写作却拓展了这件乐器的全部诗意。夜曲、叙事曲、玛祖卡、波洛涅兹里既有沙龙的优雅,也有波兰的乡愁与民族气节。三十九岁病逝于巴黎。"},
"Robert Schumann":{zh:"罗伯特·舒曼",born:1810,died:1856,country:"德国",role:"作曲家 · 乐评家",bio:"德国浪漫主义的核心人物,把文学的想象与私密的情感注入音乐。钢琴套曲《童年情景》《狂欢节》诗意盎然,艺术歌曲深情款款。晚年受精神疾病折磨,投河获救后病逝。"},
"Felix Mendelssohn":{zh:"费利克斯·门德尔松",born:1809,died:1847,country:"德国",role:"作曲家 · 指挥家",bio:"浪漫时代的古典主义者,旋律优雅、结构清晰。他十七岁写出《仲夏夜之梦》序曲,并亲手让巴赫的《马太受难曲》重见天日,推动了巴赫复兴。小提琴协奏曲家喻户晓。"},
"Hector Berlioz":{zh:"埃克托·柏辽兹",born:1803,died:1869,country:"法国",role:"作曲家",bio:"法国浪漫主义的狂想家,配器法的革命者。《幻想交响曲》以固定乐思讲述自传式的爱情迷梦,开创了标题音乐的新纪元。他的乐队想象力大胆瑰丽,领先时代。"},
"Johannes Brahms":{zh:"约翰内斯·勃拉姆斯",born:1833,died:1897,country:"德国",role:"作曲家",bio:"古典传统在浪漫时代的守护者,被视为‘贝多芬的继承人’。他的四部交响曲结构严谨、情感深沉,室内乐与《德意志安魂曲》尤为动人。严于律己,酝酿二十余年才敢发表第一交响曲。"},
"Franz Liszt":{zh:"弗朗茨·李斯特",born:1811,died:1886,country:"匈牙利",role:"作曲家 · 钢琴家",bio:"史上最伟大的钢琴炫技家,引发了欧洲的‘李斯特狂热’。他发明了交响诗,把钢琴的技术与表现力推向极限,晚年皈依宗教,音乐转向内省甚至预示了现代的无调性。"},
"Giuseppe Verdi":{zh:"朱塞佩·威尔第",born:1813,died:1901,country:"意大利",role:"作曲家",bio:"意大利歌剧之王,也是民族统一的精神象征。从《茶花女》《弄臣》到晚年的《奥赛罗》《法尔斯塔夫》,他把戏剧张力与人性刻画不断推向新高,旋律至今响彻世界各大歌剧院。"},
"Richard Wagner":{zh:"理查·瓦格纳",born:1813,died:1883,country:"德国",role:"作曲家",bio:"歌剧史上最具革命性也最具争议的人物。他以‘乐剧’与‘整体艺术作品’的理念、无尽的旋律与主导动机,彻底重塑了歌剧。《尼伯龙根的指环》长达十五小时,《特里斯坦》松动了调性的根基。"},
"Pyotr Ilyich Tchaikovsky":{zh:"彼得·伊里奇·柴科夫斯基",born:1840,died:1893,country:"俄国",role:"作曲家",bio:"俄罗斯最受欢迎的作曲家,以无与伦比的旋律天赋打动全世界。芭蕾《天鹅湖》《胡桃夹子》、钢琴协奏曲与《悲怆》交响曲将忧郁与华丽熔于一炉,情感直击人心。"},
"Antonín Dvořák":{zh:"安东宁·德沃夏克",born:1841,died:1904,country:"捷克",role:"作曲家",bio:"波希米亚的民族之声。他把捷克民间舞曲的活力融入交响曲与室内乐,旅美期间写下《自新大陆》交响曲与大提琴协奏曲,乡愁与新世界的气息交织,旋律亲切动人。"},
"Edvard Grieg":{zh:"爱德华·格里格",born:1843,died:1907,country:"挪威",role:"作曲家 · 钢琴家",bio:"挪威民族乐派的代表,把北欧的民间曲调与自然意象写进音乐。钢琴协奏曲、《培尔·金特》组曲与大量抒情钢琴小品清新如峡湾晨雾,是浪漫主义中最有地方色彩的声音之一。"},
"Modest Mussorgsky":{zh:"莫杰斯特·穆索尔斯基",born:1839,died:1881,country:"俄国",role:"作曲家",bio:"俄罗斯‘强力集团’中最富原创性的一员,追求粗粝真实的民族之声。歌剧《鲍里斯·戈杜诺夫》与钢琴组曲《图画展览会》充满力量与色彩,尽管一生潦倒、英年早逝。"},
"Gustav Mahler":{zh:"古斯塔夫·马勒",born:1860,died:1911,country:"奥地利",role:"作曲家 · 指挥家",bio:"晚期浪漫主义交响曲的集大成者。他说‘交响曲应该像世界一样,包罗万象’,把民歌、军号、葬礼与天堂塞进庞大的九部交响曲。生前以指挥闻名,身后其音乐才征服世界。"},
"Giacomo Puccini":{zh:"贾科莫·普契尼",born:1858,died:1924,country:"意大利",role:"作曲家",bio:"威尔第之后最伟大的意大利歌剧作曲家,旋律天赋无人能及。《波希米亚人》《托斯卡》《蝴蝶夫人》《图兰朵》以浓烈的抒情与真实主义的戏剧,牢牢占据世界歌剧院的中心。"},
"Richard Strauss":{zh:"理查·施特劳斯",born:1864,died:1949,country:"德国",role:"作曲家 · 指挥家",bio:"晚期浪漫的最后一位大师。他的交响诗《查拉图斯特拉如是说》《英雄生涯》炫目辉煌,歌剧《莎乐美》《玫瑰骑士》大胆华美,晚年的《最后四首歌》则以夕阳般的从容告别人世。"},
"Edward Elgar":{zh:"爱德华·埃尔加",born:1857,died:1934,country:"英国",role:"作曲家",bio:"英国音乐复兴的旗帜。《谜语变奏曲》《威风堂堂进行曲》让英国重回作曲版图,大提琴协奏曲则以一战后的挽歌气息成为二十世纪最动人的作品之一。"},
"Jean Sibelius":{zh:"让·西贝柳斯",born:1865,died:1957,country:"芬兰",role:"作曲家",bio:"芬兰的民族英雄。交响诗《芬兰颂》成为民族独立的象征,七部交响曲以严整的结构与北欧的冷峻自成一格。晚年封笔三十年,留下沉默的传奇。"},
"Sergei Rachmaninoff":{zh:"谢尔盖·拉赫玛尼诺夫",born:1873,died:1943,country:"俄国 / 美国",role:"作曲家 · 钢琴家",bio:"最后的浪漫主义者,也是二十世纪最伟大的钢琴家之一。他的第二、第三钢琴协奏曲与《帕格尼尼主题狂想曲》旋律浓情绵长。俄国革命后流亡美国,乡愁成为他音乐永恒的底色。"},
"Claude Debussy":{zh:"克劳德·德彪西",born:1862,died:1918,country:"法国",role:"作曲家",bio:"印象主义音乐的开创者,现代音乐的先知。他模糊调性、解放和声与音色,用《牧神午后》《大海》《前奏曲》描绘光影、水波与梦境,彻底改变了人们对声音的想象。"},
"Maurice Ravel":{zh:"莫里斯·拉威尔",born:1875,died:1937,country:"法国",role:"作曲家",bio:"‘瑞士钟表匠’般精密的配器大师。他的《波莱罗》《达夫尼斯与克洛埃》《西班牙狂想曲》色彩绚烂、结构无懈可击,兼有古典的克制与感官的华美,是管弦乐配器的典范。"},
"Igor Stravinsky":{zh:"伊戈尔·斯特拉文斯基",born:1882,died:1971,country:"俄国 / 美国",role:"作曲家",bio:"二十世纪最具影响力的作曲家。《春之祭》以原始的节奏引发骚乱、劈开了现代音乐的纪元。此后他不断变身——从原始主义到新古典,再到晚年的序列主义,始终引领潮流。"},
"Béla Bartók":{zh:"贝拉·巴托克",born:1881,died:1945,country:"匈牙利",role:"作曲家 · 民族音乐学家",bio:"现代音乐的巨匠,也是民族音乐学的先驱。他跋涉乡野采集匈牙利、罗马尼亚的民歌,并将其粗粝的活力与严密的现代结构熔铸成弦乐四重奏、《乐队协奏曲》等杰作。流亡美国、贫病中辞世。"},
"Sergei Prokofiev":{zh:"谢尔盖·普罗科菲耶夫",born:1891,died:1953,country:"俄国 / 苏联",role:"作曲家 · 钢琴家",bio:"兼具尖锐的现代锋芒与俄式抒情的天才。芭蕾《罗密欧与朱丽叶》《灰姑娘》、钢琴协奏曲与《彼得与狼》广受喜爱。他与斯大林在同一天去世,讣告被领袖的死讯淹没。"},
"Dmitri Shostakovich":{zh:"德米特里·肖斯塔科维奇",born:1906,died:1975,country:"苏联",role:"作曲家",bio:"在斯大林极权阴影下坚持创作的良心。他的十五部交响曲与十五部弦乐四重奏时而高呼、时而暗讽,在官方要求与内心真实之间走钢丝,是二十世纪最深刻的音乐见证者之一。"},
"Arnold Schoenberg":{zh:"阿诺德·勋伯格",born:1874,died:1951,country:"奥地利 / 美国",role:"作曲家",bio:"无调性与十二音技法的开创者,二十世纪音乐最具决定性的革命者。他从晚期浪漫的《升华之夜》一路走向调性的解体,与学生贝尔格、韦伯恩组成‘第二维也纳乐派’,重写了作曲的规则。"},
"Alban Berg":{zh:"阿尔班·贝尔格",born:1885,died:1935,country:"奥地利",role:"作曲家",bio:"勋伯格的学生,第二维也纳乐派中最富抒情性的一位。他把十二音技法与浪漫的情感、传统的形式调和,歌剧《沃采克》与《小提琴协奏曲》证明先锋语言也能催人泪下。"},
"Benjamin Britten":{zh:"本杰明·布里顿",born:1913,died:1976,country:"英国",role:"作曲家 · 指挥家 · 钢琴家",bio:"二十世纪英国最伟大的作曲家。歌剧《彼得·格莱姆斯》让英国歌剧重生,《战争安魂曲》是震撼人心的和平宣言,《青少年管弦乐指南》则家喻户晓。他的音乐兼具现代性与深切的人文关怀。"},
"Aaron Copland":{zh:"阿隆·科普兰",born:1900,died:1990,country:"美国",role:"作曲家",bio:"‘美国音乐的院长’。他以开阔明朗的和声塑造了美国的声音——《阿巴拉契亚之春》《牧区竞技》《平凡人的号角》描绘辽阔的西部与拓荒精神,亲切、乐观而崇高。"},
"George Gershwin":{zh:"乔治·格什温",born:1898,died:1937,country:"美国",role:"作曲家 · 钢琴家",bio:"横跨古典与流行、百老汇与音乐厅的天才。《蓝色狂想曲》把爵士带进音乐厅,歌剧《波吉与贝丝》则是美国歌剧的里程碑。三十八岁因脑瘤骤逝,留下无尽惋惜。"},
"Carl Orff":{zh:"卡尔·奥尔夫",born:1895,died:1982,country:"德国",role:"作曲家 · 音乐教育家",bio:"以清唱剧《布兰诗歌》名垂青史——那原始有力的节奏与《哦,命运女神》的合唱早已成为流行文化符号。他还创立了影响深远的奥尔夫音乐教学法。"},
"Olivier Messiaen":{zh:"奥利维埃·梅西安",born:1908,died:1992,country:"法国",role:"作曲家 · 管风琴师",bio:"二十世纪最独特的声音。虔诚的天主教徒、痴迷的鸟类学家、色彩联觉者,他把宗教的狂喜、鸟鸣的记谱与异国节奏熔铸成前所未有的音响。《为时间终结而作的四重奏》在战俘营中诞生。"},
"Henryk Górecki":{zh:"亨里克·戈雷茨基",born:1933,died:2010,country:"波兰",role:"作曲家",bio:"波兰作曲家,早年写先锋音乐,后转向深沉的调性与宗教情怀。《第三交响曲“悲歌交响曲”》以缓慢的哀歌抚慰人心,1992年的录音意外售出百万张,成为神圣极简主义的象征。"},
"Arvo Pärt":{zh:"阿沃·帕尔特",born:1935,country:"爱沙尼亚",role:"作曲家",bio:"当今最常被演奏的在世作曲家之一。他发明的‘钟鸣作曲法’(tintinnabuli)以最简的三和弦与音阶营造出祈祷般的澄澈静谧,《镜中镜》《圣母颂》抚慰了无数现代心灵。"},
"Steve Reich":{zh:"史蒂夫·赖希",born:1936,country:"美国",role:"作曲家",bio:"简约主义的奠基者之一。他以‘相位偏移’与持续脉动的循环织体重塑了节奏的听感,《为18位音乐家而作的音乐》《不同的火车》影响遍及古典、电子与流行乐界。"},
"Philip Glass":{zh:"菲利普·格拉斯",born:1937,country:"美国",role:"作曲家",bio:"当代最高产、最广为人知的作曲家之一。他标志性的琶音循环与渐变结构贯穿歌剧(《海滩上的爱因斯坦》)、交响曲与大量电影配乐(《时时刻刻》),把简约主义带给了大众。"},
"John Adams":{zh:"约翰·亚当斯",born:1947,country:"美国",role:"作曲家 · 指挥家",bio:"后简约主义的代表人物,在赖希、格拉斯的脉动之上重新注入浪漫的情感与交响的宏大。歌剧《尼克松在中国》、管弦乐《颤木环》《和声学》充满美式的活力与光辉。"},
"György Ligeti":{zh:"捷尔吉·利盖蒂",born:1923,died:2006,country:"匈牙利 / 奥地利",role:"作曲家",bio:"二十世纪下半叶最富想象力的作曲家。他的‘微复调’音簇因库布里克电影《2001太空漫游》而广为人知,晚年的《钢琴练习曲》融合非洲节奏与分形几何,狂放而精密。"},
"Krzysztof Penderecki":{zh:"克日什托夫·潘德列茨基",born:1933,died:2020,country:"波兰",role:"作曲家 · 指挥家",bio:"波兰先锋音乐的旗帜。早期以《广岛受难者挽歌》等‘音响主义’作品震撼乐坛,用音簇与非常规奏法开拓声音的疆界;后期回归更具调性的宏大风格。其音乐亦常见于恐怖电影配乐。"}
};

// ---- 组装 ----
Object.assign(BIOS, BIOS2);
const ALBUMS = R.concat(R2).map((row,i)=>{
  const [t,zh,c,perf,y,label,era,g,ins,m,r] = row;
  return {id:String(i+1).padStart(4,"0"), title:t, zh, artist:c, perf, year:y, label, era, genres:g, instruments:ins, moods:m, reason:r};
});

// 校验：era / bios 引用有效性
const eraKeys = new Set(ERAS.map(e=>e.key));
let warn=0;
ALBUMS.forEach(a=>{ if(!eraKeys.has(a.era)){console.warn("BAD era",a.id,a.era);warn++;} });
const composers = new Set(ALBUMS.map(a=>a.artist));
composers.forEach(c=>{ if(!BIOS[c]) console.warn("NO bio:",c); });
console.log("recordings:",ALBUMS.length,"| composers:",composers.size,"| bios:",Object.keys(BIOS).length,"| warnings:",warn);

const banner = "/* 1001 Classical data layer — window.ALBUMS = 策展古典录音（每条为公认标杆/传奇录音）。自动生成，勿手改。 */\n";
const out =
  banner +
  "window.ERAS = " + JSON.stringify(ERAS) + ";\n" +
  "window.MOODS = " + JSON.stringify(MOODS) + ";\n" +
  "window.INSTRUMENTS = " + JSON.stringify(INSTRUMENTS) + ";\n" +
  "window.FEATURED_ARTISTS = " + JSON.stringify(FEATURED) + ";\n" +
  "window.ALBUMS = [\n" + ALBUMS.map(a=>JSON.stringify(a)).join(",\n") + "\n];\n";
writeFileSync("data.js", out);

const biosBanner =
`/* 1001 Classical — 作曲家小传（window.ARTIST_BIOS）。键 = 录音数据里的 artist（作曲家英文名）。
 * 字段：zh 译名 · born/died 生卒（在世者省略 died；乐派/群体用 life）· country 国别 · role 身份 · bio 中文小传。
 * 缺省优雅降级：无小传的作曲家仍正常显示作品列表。自动生成，勿手改。 */\n`;
writeFileSync("composers.js", biosBanner + "window.ARTIST_BIOS = " + JSON.stringify(BIOS,null,0) + ";\n");
console.log("wrote data.js + composers.js");
